import re

def orgName(text):
    """Apply tags to the regex

    :param text str: organization that has to be encoded
    :returns: organization encoded with the proper tags
    :rtype: str
    """

    #This series of statements contains regex of organizations from the corpus
    g0001 = re.compile(r"C(arnegie|ARNEGIE) E(ndowment|NDOWMENT)")
    g0001bis = re.compile(r"D(otation|OTATION|OATATION) (c|C)(arnegie|ARNEGIE)")
    g0001ter = re.compile(r"Fondation Carnegie")
    g0002 = re.compile(r"S(énat|ÉNAT|ENAT)( (a|A)méricain)?")
    g0003 = re.compile(r"29ème Chasseurs")
    g0004 = re.compile(r"2e Division")
    g0005 = re.compile(r"Académie des inscriptions")
    g0006 = re.compile(r"Académie des Sciences( Morales)?")
    g0008 = re.compile(r"A(cadémie|CADÉMIE) F(rançaise|RANCAISE)")
    g0009 = re.compile(r"Action Française")
    g0010 = re.compile(r"Aéro-Club américain")
    g0011 = re.compile(r"Aéro-Club de France")
    g0012 = re.compile(r"Affaires Etrang(e|è)res( de Russie)?")
    g0014 = re.compile(r"Agence Fournier")
    g0015 = re.compile(r"Agence(s) Havas")
    g0016 = re.compile(r"Air Board")
    g0017 = re.compile(r"A(merican|MERICAN) (c|C)(LUB|lub)( de Paris| DE PARIS)?")
    g0018 = re.compile(r"American Review of Reviews")
    g0019 = re.compile(r"Assemblée Nationale")
    g0020 = re.compile(r"Banque de France")
    g0021 = re.compile(r"B(erkely|ERKELY) U(niversity|NIVERSITY)")
    g0023 = re.compile(r"Chambre des Députés")
    g0024 = re.compile(r"C(olumbia|OLUMBIA)( University)?")
    g0025 = re.compile(r"Croix Rouge")
    g0026 = re.compile(r"Douma")
    g0027 = re.compile(r"Ecole de Joinville")
    g0028 = re.compile(r"Ecole de P(au|AU)")
    g0029 = re.compile(r"Ecole de St-Cyr")
    g0030 = re.compile(r"Ecole de tir aérien")
    g0031 = re.compile(r"Ecole des Grenadiers")
    g0032 = re.compile(r"Ecole des Sciences Morales")
    g0033 = re.compile(r"Ecole Normale")
    g0034 = re.compile(r"Entente Cordiale")
    g0035 = re.compile(r"Etat(-| )Major allemand")
    g0036 = re.compile(r"Faculté de Droit( de Paris)?")
    g0037 = re.compile(r"Faculté(s)? des Lettres( de Paris)?")
    g0038 = re.compile(r"Faculté des Sciences( de Paris)?")
    g0039 = re.compile(r"Fédération Nationale de la Mutualité")
    g0040 = re.compile(r"Ford")
    g0041 = re.compile(r"Garde Républicaine")
    g0042 = re.compile(r"Gardes Ecossais")
    g0043 = re.compile(r"Gardes Municipaux")
    g0044 = re.compile(r"Havas")
    g0045 = re.compile(r"Institut Américain")
    g0046 = re.compile(r"I(NSTITUT|nstitut) (D|d)('|’)(OPTIOUE|optique)")
    g0047 = re.compile(r"Institut National des Arts et des Lettres")
    g0048 = re.compile(r"Institut Pasteur")
    g0049 = re.compile(r"MORGAN HARJES")
    g0050 = re.compile(r"P(arlement|ARLEMENT)( (b|B)ritannique)?( (f|F)(rançais|RANCAIS))?( anglais)?( italien)?( Russe)?")
    g0055 = re.compile(r"Quakers")
    g0056 = re.compile(r"Régiment du 110 ème d'Infanterie")
    g0057 = re.compile(r"R(eichstag|EICHSTAG)")
    g0059 = re.compile(r"SOCIETE de l'HISTOIRE de la GUERRE")
    g0060 = re.compile(r"S(ociété|ocieté|OCIETE|OCIÉTÉ) (de(s)?|DES|of)( |/)N(ations|ATIONS)")
    g0061 = re.compile(r"Société des Beaux-Arts")
    g0062 = re.compile(r"Société (p|P)éruvienne( de Droit International)?")
    g0063 = re.compile(r"Société Suisse Genevoise")
    g0064 = re.compile(r"U(NION|nion) (DE|de(s)?) A(SSOCIATIONS|ssociations)( INTERNATIONALES)?")
    g0065 = re.compile(r"Union Française")
    g0066 = re.compile(r"(U|u)nion (I|i)nterallié(e)?")
    g0067 = re.compile(r"Union Interparlementaire")
    g0068 = re.compile(r"Union League club de Philadelphie")
    g0069 = re.compile(r"union républicaine")
    g0070 = re.compile(r"Union sacrée contre l'Allemagne")
    g0071 = re.compile(r"United States corporation")
    g0072 = re.compile(r"Université de Harward")
    g0073 = re.compile(r"U(niversité de Paris|NIVERSITÉ DE PARIS)")
    g0074 = re.compile(r"War Office")
    g0075 = re.compile(r"Y.M.C.A.")
    g0076 = re.compile(r"Zemstvos")


    #This series of statements contains the encoding for the organizations from the corpus
    text = re.sub(g0001, r'<orgName ref="#g0001" type="pec">\g<0></orgName>', text)
    text = re.sub(g0001bis, r'<orgName ref="#g0001" type="pec">\g<0></orgName>', text)
    text = re.sub(g0001ter, r'<orgName ref="#g0001" type="pec">\g<0></orgName>', text)
    text = re.sub(g0002, r'<orgName ref="#g0002" type="pec">\g<0></orgName>', text)
    text = re.sub(g0003, r'<orgName ref="#g0003" type="pec">\g<0></orgName>', text)
    text = re.sub(g0004, r'<orgName ref="#g0004" type="pec">\g<0></orgName>', text)
    text = re.sub(g0005, r'<orgName ref="#g0005" type="pec">\g<0></orgName>', text)
    text = re.sub(g0006, r'<orgName ref="" type="pec">\g<0></orgName>', text)
    text = re.sub(g0008, r'<orgName ref="#g0008" type="pec">\g<0></orgName>', text)
    text = re.sub(g0009, r'<orgName ref="#g0009" type="pec">\g<0></orgName>', text)
    text = re.sub(g0010, r'<orgName ref="#g0010" type="pec">\g<0></orgName>', text)
    text = re.sub(g0011, r'<orgName ref="#g0011" type="pec">\g<0></orgName>', text)
    text = re.sub(g0012, r'<orgName ref="" type="pec">\g<0></orgName>', text)
    text = re.sub(g0014, r'<orgName ref="#g0014" type="pec">\g<0></orgName>', text)
    text = re.sub(g0015, r'<orgName ref="#g0015" type="pec">\g<0></orgName>', text)
    text = re.sub(g0016, r'<orgName ref="#g0016" type="pec">\g<0></orgName>', text)
    text = re.sub(g0017, r'<orgName ref="#g0017" type="pec">\g<0></orgName>', text)
    text = re.sub(g0018, r'<orgName ref="#g0018" type="pec">\g<0></orgName>', text)
    text = re.sub(g0019, r'<orgName ref="#g0019" type="pec">\g<0></orgName>', text)
    text = re.sub(g0020, r'<orgName ref="#g0020" type="pec">\g<0></orgName>', text)
    text = re.sub(g0021, r'<orgName ref="#g0021" type="pec">\g<0></orgName>', text)
    text = re.sub(g0023, r'<orgName ref="#g0023" type="pec">\g<0></orgName>', text)
    text = re.sub(g0024, r'<orgName ref="#g0024" type="pec">\g<0></orgName>', text)
    text = re.sub(g0025, r'<orgName ref="#g0025" type="pec">\g<0></orgName>', text)
    text = re.sub(g0026, r'<orgName ref="#g0026" type="pec">\g<0></orgName>', text)
    text = re.sub(g0027, r'<orgName ref="#g0027" type="pec">\g<0></orgName>', text)
    text = re.sub(g0028, r'<orgName ref="#g0028" type="pec">\g<0></orgName>', text)
    text = re.sub(g0029, r'<orgName ref="#g0029" type="pec">\g<0></orgName>', text)
    text = re.sub(g0030, r'<orgName ref="#g0030" type="pec">\g<0></orgName>', text)
    text = re.sub(g0031, r'<orgName ref="#g0031" type="pec">\g<0></orgName>', text)
    text = re.sub(g0032, r'<orgName ref="#g0032" type="pec">\g<0></orgName>', text)
    text = re.sub(g0033, r'<orgName ref="#g0033" type="pec">\g<0></orgName>', text)
    text = re.sub(g0034, r'<orgName ref="#g0034" type="pec">\g<0></orgName>', text)
    text = re.sub(g0035, r'<orgName ref="#g0035" type="pec">\g<0></orgName>', text)
    text = re.sub(g0036, r'<orgName ref="#g0036" type="pec">\g<0></orgName>', text)
    text = re.sub(g0037, r'<orgName ref="#g0037" type="pec">\g<0></orgName>', text)
    text = re.sub(g0038, r'<orgName ref="#g0038" type="pec">\g<0></orgName>', text)
    text = re.sub(g0039, r'<orgName ref="#g0039" type="pec">\g<0></orgName>', text)
    text = re.sub(g0040, r'<orgName ref="#g0040" type="pec">\g<0></orgName>', text)
    text = re.sub(g0041, r'<orgName ref="#g0041" type="pec">\g<0></orgName>', text)
    text = re.sub(g0042, r'<orgName ref="#g0042" type="pec">\g<0></orgName>', text)
    text = re.sub(g0043, r'<orgName ref="#g0043" type="pec">\g<0></orgName>', text)
    text = re.sub(g0044, r'<orgName ref="#g0044" type="pec">\g<0></orgName>', text)
    text = re.sub(g0045, r'<orgName ref="#g0045" type="pec">\g<0></orgName>', text)
    text = re.sub(g0046, r'<orgName ref="#g0046" type="pec">\g<0></orgName>', text)
    text = re.sub(g0047, r'<orgName ref="#g0047" type="pec">\g<0></orgName>', text)
    text = re.sub(g0048, r'<orgName ref="#g0048" type="pec">\g<0></orgName>', text)
    text = re.sub(g0049, r'<orgName ref="#g0049" type="pec">\g<0></orgName>', text)
    text = re.sub(g0050, r'<orgName ref="#g0050" type="pec">\g<0></orgName>', text)
    text = re.sub(g0055, r'<orgName ref="#g0055" type="pec">\g<0></orgName>', text)
    text = re.sub(g0056, r'<orgName ref="#g0056" type="pec">\g<0></orgName>', text)
    text = re.sub(g0057, r'<orgName ref="#g0057" type="pec">\g<0></orgName>', text)
    text = re.sub(g0059, r'<orgName ref="#g0059" type="pec">\g<0></orgName>', text)
    text = re.sub(g0060, r'<orgName ref="#g0060" type="pec">\g<0></orgName>', text)
    text = re.sub(g0061, r'<orgName ref="#g0061" type="pec">\g<0></orgName>', text)
    text = re.sub(g0062, r'<orgName ref="#g0062" type="pec">\g<0></orgName>', text)
    text = re.sub(g0063, r'<orgName ref="#g0063" type="pec">\g<0></orgName>', text)
    text = re.sub(g0064, r'<orgName ref="#g0064" type="pec">\g<0></orgName>', text)
    text = re.sub(g0065, r'<orgName ref="#g0065" type="pec">\g<0></orgName>', text)
    text = re.sub(g0066, r'<orgName ref="#g0066" type="pec">\g<0></orgName>', text)
    text = re.sub(g0067, r'<orgName ref="#g0067" type="pec">\g<0></orgName>', text)
    text = re.sub(g0068, r'<orgName ref="#g0068" type="pec">\g<0></orgName>', text)
    text = re.sub(g0069, r'<orgName ref="#g0069" type="pec">\g<0></orgName>', text)
    text = re.sub(g0070, r'<orgName ref="#g0070" type="pec">\g<0></orgName>', text)
    text = re.sub(g0071, r'<orgName ref="#g0071" type="pec">\g<0></orgName>', text)
    text = re.sub(g0072, r'<orgName ref="#g0072" type="pec">\g<0></orgName>', text)
    text = re.sub(g0073, r'<orgName ref="#g0073" type="pec">\g<0></orgName>', text)
    text = re.sub(g0074, r'<orgName ref="#g0074" type="pec">\g<0></orgName>', text)
    text = re.sub(g0075, r'<orgName ref="#g0075" type="pec">\g<0></orgName>', text)
    text = re.sub(g0076, r'<orgName ref="#g0076" type="pec">\g<0></orgName>', text)
    return text