import re

def persName(text):
    """Apply tags to the regex

    :param text str: person that has to be encoded
    :returns: person encoded with the proper tag
    :rtype: str
    """

    #This series of statements contains regex of persons from the corpus
    p0001 = re.compile(r"(Madame )?(M. ?)?(Baron )?(D|d)('|’)E(STOURNELLES|stournelles)( (de|DE) C(ONSTANT|onstant))?")
    p0002 = re.compile(r"((M(.|onsieur|adame) ?)?((le )?P(résident|RÉSIDENT) ?)?((N|H)(.|icholas)? ?)?(M(urray|.) ?)?)?B(u(l)?tler|UTLER)")
    p0003 = re.compile(r"Major ABBOTT")
    p0004 = re.compile(r"M. Abrami")
    p0005 = re.compile(r"Paul Adam")
    p0006 = re.compile(r"(M.|(B|b)aron) A(delsward|DELSWARD)")
    p0007 = re.compile(r"Felix Alcan")
    p0008 = re.compile(r"Miss Alexander")
    p0009 = re.compile(r"Alexandre le Grand")
    p0010 = re.compile(r"Almereyda")
    p0011 = re.compile(r"Amelot")
    p0012 = re.compile(r"(M(e)?lle.? ?) A(MELOT|melot)")
    p0013 = re.compile(r"(C|c)ardinal Amette")
    p0014 = re.compile(r"FERN ANDREWS")
    p0015 = re.compile(r"ANDRIEUX")
    p0016 = re.compile(r"ANGELL")
    p0017 = re.compile(r"Anibal MAURTUA")
    p0018 = re.compile(r"Anselmo V. BARRETO")
    p0019 = re.compile(r"(M.|Alexandre) ANTONIADES (Alexandre )")
    p0020 = re.compile(r"Antonio MUO")
    p0021 = re.compile(r"((M.)? ?(P.)?(Paul)? )?A(ppell|PPELL)")
    p0022 = re.compile(r"Apponyi")
    p0023 = re.compile(r"Archimède")
    p0024 = re.compile(r"Aristide Briand")
    p0025 = re.compile(r"Armez")
    p0026 = re.compile(r"Artaban")
    p0027 = re.compile(r"Arturo GARCIA")
    p0028 = re.compile(r"Attila")
    p0029 = re.compile(r"Amiral Aube")
    p0030 = re.compile(r"Révérend J.B.ASHAM")
    p0031 = re.compile(r"Aubigné")
    p0032 = re.compile(r"Augagneur")
    p0033 = re.compile(r"Auguste Gauvain")
    p0034 = re.compile(r"Auguste Lalance")
    p0035 = re.compile(r"(M. )?A(ulard|ULARD)")
    p0036 = re.compile(r"Bach")
    p0037 = re.compile(r"(Robert )?Bacon")
    p0038 = re.compile(r"Major BAIRD")
    p0039 = re.compile(r"((A|M). )?Balfour")
    p0040 = re.compile(r"Balzac")
    p0041 = re.compile(r"Barbosa")
    p0042 = re.compile(r"B(arbusse|ARBUSSE)")
    p0043 = re.compile(r"((M.|Maurice) )?Barrès")
    p0044 = re.compile(r"Jean Bart")
    p0045 = re.compile(r"((L.|M.|Louis) )?Barthou")
    p0046 = re.compile(r"Batut")
    p0047 = re.compile(r"Bazelaire")
    p0048 = re.compile(r"Beaumarchais")
    p0049 = re.compile(r"((M. )?(Louis D.)? )?Beaumont")
    p0050 = re.compile(r"B(EETHOVEN|EETHOVEN)")
    p0051 = re.compile(r"Victor Andres BELAUNDE")
    p0052 = re.compile(r"(Alexandre )?Bérard")
    p0053 = re.compile(r"((M.|Henry) )?B(e|é)renger")
    p0054 = re.compile(r"Emile BERGERAT")
    p0055 = re.compile(r"((H|M). )?B(ergson|ERGSON)")
    p0056 = re.compile(r"Maurice Bernard")
    p0057 = re.compile(r"Edouard Bernstein")
    p0058 = re.compile(r"BERTHELOT")
    p0059 = re.compile(r"(Mlle.? )?B(érubet|ERUBET)")
    p0060 = re.compile(r"Bethmann-Holweg")
    p0061 = re.compile(r"M. Bickoff")
    p0062 = re.compile(r"Paul B(ignon|IGNON)")
    p0063 = re.compile(r"BIGNON (Paul )")
    p0065 = re.compile(r"Bismarck")
    p0066 = re.compile(r"(Vidal de la )?B(LACHE|lache)")
    p0067 = re.compile(r"Louis Blanc")
    p0068 = re.compile(r"J(.|ulien) Bled")
    p0069 = re.compile(r"Blériot")
    p0070 = re.compile(r"BLUM")
    p0071 = re.compile(r"Blumenthal")
    p0072 = re.compile(r"(Léon )?Boll")
    p0073 = re.compile(r"Bolo")
    p0074 = re.compile(r"Paul BONCOUR")
    p0075 = re.compile(r"(Gaston )?B(onnier|ONNIER)")
    p0076 = re.compile(r"Sir Robert BORDEN")
    p0078 = re.compile(r"Bouffard")
    p0079 = re.compile(r"Bouglé")
    p0080 = re.compile(r"Bourdillon")
    p0081 = re.compile(r"(G(eorges|.) )?(N)?B(ourdon|OURDON) (G. )")
    p0082 = re.compile(r"((M. ?)?(L. )?(Léon )?)?B(our(n)?geois|OURGEOIS)")
    p0083 = re.compile(r"(Paul )?Bourget")
    p0084 = re.compile(r"M. Boutroux")
    p0085 = re.compile(r"B(rashear|RASHEAR)")
    p0087 = re.compile(r"R(e|é)v(e|é)rend Charles H. B(RENT|rent)")
    p0088 = re.compile(r"E.Briat")
    p0089 = re.compile(r"((M. )?(A. ?)? )?B(riand|RIAND)")
    p0090 = re.compile(r"BRIEUX")
    p0091 = re.compile(r"Commandant BRIGGS")
    p0092 = re.compile(r"Brisson")
    p0093 = re.compile(r"(Dr.|M.) Broda")
    p0094 = re.compile(r"Brout")
    p0095 = re.compile(r"((M. )?(James |John )?)?Brown S(cott|SCOTT)")
    p0096 = re.compile(r"(J.W.|M. W.|M. W.J.|W.J.) B(ryan|RYAN)")
    p0097 = re.compile(r"Lord B(ryce|RYCE)")
    p0099 = re.compile(r"(Ferdinand |P. ?)?B(uisson|UISSON)")
    p0100 = re.compile(r"Bulöw")
    p0101 = re.compile(r"Buquin (Dr. )")
    p0103 = re.compile(r"Henry Cabot Lodge")
    p0104 = re.compile(r"((M. )?(Marcel )?)?C(achin|ACHIN)")
    p0105 = re.compile(r"Général Cadorna")
    p0106 = re.compile(r"((Mme.? ?)(M. )?(Joseph )?)?C(aillaux|AILLAUX)")
    p0107 = re.compile(r"Calmette")
    p0108 = re.compile(r"(Ambassadeur Paul |((M. )?(J(ules|ULES) )?))?C(ambon|AMBON)")
    p0109 = re.compile(r"Général Cambronne")
    p0110 = re.compile(r"Camille Bloch")
    p0111 = re.compile(r"Campbell Pannermann")
    p0113 = re.compile(r"(M(.|adame|me.? ?) )?(A(. |ndrew )?)?C(arnegie|ARNEGIE)")
    p0115 = re.compile(r"(Sadi-|Adolphe )?C(arnot|ARNOT)")
    p0116 = re.compile(r"Carnot (Sadi-)")
    p0117 = re.compile(r"Eugène Carrière")
    p0118 = re.compile(r"(Gustave )?Cauvin")
    p0119 = re.compile(r"Miss Cavell")
    p0120 = re.compile(r"César Fran(c)?k")
    p0121 = re.compile(r"M. Cestre")
    p0122 = re.compile(r"Oliver M. CHADWICK")
    p0123 = re.compile(r" (Mme.? ?)?Chamberlain")
    p0125 = re.compile(r"Chancelier Hertling")
    p0126 = re.compile(r"Changy")
    p0127 = re.compile(r"Chaptal")
    p0128 = re.compile(r"Charlemagne")
    p0129 = re.compile(r"Francis Charmes")
    p0130 = re.compile(r"Chartier")
    p0131 = re.compile(r"Chauchard")
    p0132 = re.compile(r"M. CHAUMET")
    p0133 = re.compile(r"((M. )?(André )?)?Chéradame")
    p0134 = re.compile(r"((M. )?(Henry )?)?Chéro(n|u)")
    p0135 = re.compile(r"Chevillard")
    p0136 = re.compile(r"((Joseph H. )?(Madame )?(Mlle.? )?)?C(HOATE|hoate)")
    p0138 = re.compile(r"(Winston )?(C|c)hurchil(l)?")
    p0139 = re.compile(r"Cincinnatus")
    p0140 = re.compile(r"(M. )?C(lauzel|LAUZEL)")
    p0141 = re.compile(r"M. Claveille")
    p0142 = re.compile(r"(M. )?C(l(e|é)menceau|LEMENCEAU)")
    p0143 = re.compile(r"(M. )?C(lémentel|LEMENTEL)")
    p0144 = re.compile(r"(Denys )?Cochin")
    p0146 = re.compile(r"M. Combes")
    p0147 = re.compile(r"Comby")
    p0148 = re.compile(r"Commodore PAYNE")
    p0149 = re.compile(r"B(.|enjamin) C(ONSTANT|onstant)")
    p0150 = re.compile(r"Constantin")
    p0151 = re.compile(r"Consuelo")
    p0152 = re.compile(r"Corréard")
    p0153 = re.compile(r"Corry")
    p0154 = re.compile(r"Cottin")
    p0155 = re.compile(r"Coubertin")
    p0156 = re.compile(r"C(ouyba|OUYBA)")
    p0157 = re.compile(r"Lord COWDRAY")
    p0158 = re.compile(r"A(.|lfred) Croiset")
    p0159 = re.compile(r"Arthur Croussier")
    p0161 = re.compile(r"Cunliffe Owen")
    p0162 = re.compile(r"Czernin")
    p0163 = re.compile(r"A(.|ndrew )D. White")
    p0164 = re.compile(r"d'Annunzio")
    p0165 = re.compile(r"d'Audigné")
    p0166 = re.compile(r"Vincent d'Indy")
    p0167 = re.compile(r"(M.|Alberto) d'O(liveira|LIVEIRA)")
    p0168 = re.compile(r"Dr. Dagincourt")
    p0169 = re.compile(r"(M. )?D(ato|ATO)")
    p0170 = re.compile(r"(Léon )?D(audet|AUDET)")
    p0171 = re.compile(r"David Starr Jordan")
    p0172 = re.compile(r"Dayton")
    p0173 = re.compile(r"(Comte|M.) de Beaumont")
    p0174 = re.compile(r"(Madame la Marquise |(Mme.? ?))de Canay")
    p0175 = re.compile(r"(M.|Baron) de Chambrun")
    p0176 = re.compile(r"comte de Dreux-Brézé")
    p0177 = re.compile(r"M. de Fleuriau")
    p0178 = re.compile(r"(Mme.? ?)de Ganay")
    p0179 = re.compile(r"(M.|(D|d)uc) de Guiche")
    p0180 = re.compile(r"Général de L(acroix|ACROIX)")
    p0181 = re.compile(r"(M. )?((A|C). )?de L(apradelle|APRADELLE)")
    p0182 = re.compile(r"(D|d)uc(hesse)? de Marlborough")
    p0183 = re.compile(r"(M.|(C|c)omte) de Nicolay")
    p0184 = re.compile(r"M. Jean de Pierrefeu")
    p0185 = re.compile(r"comte de Rougé pour Sablé")
    p0186 = re.compile(r"Madame de Saint-Gervais")
    p0187 = re.compile(r"(M. ?) (J. )?de Sillac")
    p0188 = re.compile(r"M. de Staal")
    p0189 = re.compile(r"M(.|arquis) de Talhouet")
    p0190 = re.compile(r"(Mme.? ?)de WITT-SCHLUMBERGER")
    p0191 = re.compile(r"D(ebove|EBOVE)")
    p0192 = re.compile(r"Decamps")
    p0193 = re.compile(r"Degas")
    p0194 = re.compile(r"Delagrave")
    p0195 = re.compile(r"(M. )?D(elcassé|ELCASSÉ)")
    p0196 = re.compile(r"Lord Derby")
    p0197 = re.compile(r"Paul Déroulède")
    p0198 = re.compile(r"Stéphane Dervillé")
    p0199 = re.compile(r"((D|d)uc )des Curs")
    p0200 = re.compile(r"Lord Desart")
    p0201 = re.compile(r"Paul Deschanel")
    p0202 = re.compile(r"Dessoye")
    p0203 = re.compile(r"M. W.J DEYAN")
    p0204 = re.compile(r"Général Diaz")
    p0205 = re.compile(r"Sir Willoughby Dickinson")
    p0206 = re.compile(r"Maurice Donnay")
    p0207 = re.compile(r"Professeur Douglas")
    p0208 = re.compile(r"((G|M|P(aul)?).) D(oumer|OUMER)")
    p0209 = re.compile(r"(Gaston )?D(oumergue|OUMERGUE)")
    p0210 = re.compile(r"D(reyfus|REYFUS)")
    p0211 = re.compile(r"Sir Eric Drummond")
    p0212 = re.compile(r"Du Guesclin")
    p0213 = re.compile(r"Président Dubost")
    p0214 = re.compile(r"(M|R). ?Dubreuilh")
    p0215 = re.compile(r"Dufayel")
    p0216 = re.compile(r"Duguay Trouin")
    p0217 = re.compile(r"(Jacques )?D(umas|UMAS)")
    p0218 = re.compile(r"Jean Dupuy")
    p0219 = re.compile(r"Durand")
    p0220 = re.compile(r"(Samuel )?Dutton")
    p0221 = re.compile(r"Duval")
    p0222 = re.compile(r"Edouard VII(I)?")
    p0224 = re.compile(r"Elbert H. GARY")
    p0225 = re.compile(r"Eledoro RONIRO")
    p0226 = re.compile(r"(Président |W.)Eliot(t)?")
    p0227 = re.compile(r"(M.|Professeur) Erskine")
    p0229 = re.compile(r"F(allière(s)?|ALLIERES)")
    p0230 = re.compile(r"Farman")
    p0231 = re.compile(r"(Félix )?Faure")
    p0232 = re.compile(r"Jules Favre")
    p0233 = re.compile(r"(L(A|a))?F(ayette|AYETTE)")
    p0234 = re.compile(r"K. Herman FERNAU")
    p0235 = re.compile(r"Jules Ferry")
    p0236 = re.compile(r"(M. )?F(inch|INCH)")
    p0237 = re.compile(r"Firmin Roz")
    p0238 = re.compile(r"(H.F.T. )?((C|c)olonel )?F(isher|ISHER)")
    p0239 = re.compile(r"Flandin")
    p0240 = re.compile(r"(Général|Maréchal) F(och|OCH)")
    p0241 = re.compile(r"(M. ?)?((le )?(P|p)rofesseur )?(F.)?(W. ?)?F(oerster|OERSTER)")
    p0242 = re.compile(r"Arthur Fontaine")
    p0243 = re.compile(r"Forain")
    p0244 = re.compile(r"Général FORBIS GLENN")
    p0245 = re.compile(r"M. Ford")
    p0246 = re.compile(r"(M. N. Wilhelm )?F(örster|ORSTER)")
    p0247 = re.compile(r"Fouqueray")
    p0248 = re.compile(r"(Amiral )?(Vice-amiral )?F(ournier|OURNIER)")
    p0249 = re.compile(r"Foy")
    p0250 = re.compile(r"Francière")
    p0251 = re.compile(r"M. Frank Harris Hitchcock")
    p0252 = re.compile(r"Franklin-Bouillon")
    p0253 = re.compile(r"Frederic COOK MOREHOUSE")
    p0254 = re.compile(r"Freycinet")
    p0255 = re.compile(r"Friat")
    p0256 = re.compile(r"(Dr.? ?)?(Alfred M. )?F(ried|RIED)")
    p0257 = re.compile(r"M. Fromageot")
    p0258 = re.compile(r"Edward FRY")
    p0259 = re.compile(r"Gainsborough")
    p0260 = re.compile(r"Galilée")
    p0261 = re.compile(r"Général Galliéni")
    p0262 = re.compile(r"L. GALLOIS")
    p0263 = re.compile(r"Gambetta")
    p0265 = re.compile(r"(Capitaine )?Garros")
    p0266 = re.compile(r"Gaudineau")
    p0267 = re.compile(r"Théophile Gautier")
    p0268 = re.compile(r"G(entilliez|ENTILLIEZ)")
    p0269 = re.compile(r"George Louis Beer")
    p0270 = re.compile(r"GERLACH")
    p0271 = re.compile(r"Germain")
    p0272 = re.compile(r"(M. )?(Charles )?G(ide|IDE)")
    p0273 = re.compile(r"Gilbert MURRAY")
    p0274 = re.compile(r"(M. )?(Edward )?G(IRETTI|iretti)")
    p0275 = re.compile(r"Gladstone")
    p0276 = re.compile(r"Comte Goblet d'Alviella")
    p0277 = re.compile(r"(M. )?(J(.|ustin) )?G(odart|ODART)")
    p0278 = re.compile(r"Goethe")
    p0279 = re.compile(r"Jean Gout")
    p0280 = re.compile(r"(Comtesse )?Gref(f)?ulhe")
    p0281 = re.compile(r"(Lord|Sir Edward) G(rey|REY)")
    p0282 = re.compile(r"M. Arthur Griggs")
    p0283 = re.compile(r"GRILLING")
    p0284 = re.compile(r"(Robert )?GRIMM")
    p0285 = re.compile(r"Amiral GUEPRATTE")
    p0286 = re.compile(r"Guernut (Henri )")
    p0287 = re.compile(r" (M. )?H(.|enri) G(UERNUT|uernut)")
    p0288 = re.compile(r"Guillan")
    p0289 = re.compile(r"Guillard")
    p0290 = re.compile(r"G(UILLAUME|uillaume) II")
    p0292 = re.compile(r"M. Guthric")
    p0293 = re.compile(r"(Mr. )?((M|B)yron )?(H|N)erri(c|e)k")
    p0294 = re.compile(r"HAASE")
    p0295 = re.compile(r"Marcel HABERT")
    p0296 = re.compile(r"M. Haguenin")
    p0297 = re.compile(r"Halévy")
    p0298 = re.compile(r"(M. )?(G(.|abriel ))?H(anot(e)?aux|ANOTAUX)")
    p0299 = re.compile(r"Harold C. Goddard")
    p0300 = re.compile(r"H(askell|ASKELL)")
    p0302 = re.compile(r"Henri Hauser")
    p0303 = re.compile(r"(J|M). HAYEZ")
    p0304 = re.compile(r"M. Hearst")
    p0305 = re.compile(r"Hébrard de Villeneuve")
    p0306 = re.compile(r"M.Helfferich")
    p0307 = re.compile(r"Général HENDERSON")
    p0308 = re.compile(r"Hercule")
    p0309 = re.compile(r"M. Herestchenko")
    p0310 = re.compile(r"Hérode")
    p0311 = re.compile(r"(E.)?H(erriot|ERRIOT)")
    p0312 = re.compile(r"Commandant Hess")
    p0313 = re.compile(r"Hindenburg")
    p0314 = re.compile(r"Hirst")
    p0316 = re.compile(r"(M. )?(Alfred )?H(olman|OLMAN)")
    p0317 = re.compile(r"(M. )?H(.|amilton) H(olt|OLT)")
    p0318 = re.compile(r"(Colonel|M.|Mme.) H(ouse|OUSE)")
    p0319 = re.compile(r"M. Houzeau( de Lehaie)?")
    p0320 = re.compile(r"M. HUA-CHEN MEI")
    p0321 = re.compile(r"(Caporal )?H(uard|UARD)")
    p0322 = re.compile(r"M. Hughes")
    p0323 = re.compile(r"Victor Hugo")
    p0325 = re.compile(r"SENATEUR HUMBERT")
    p0326 = re.compile(r"Hymans")
    p0327 = re.compile(r"Ireneu Machado")
    p0328 = re.compile(r"Isadora Duncan")
    p0329 = re.compile(r"Israël Lévi")
    p0331 = re.compile(r"Mme.? ?James Brown Scott")
    p0332 = re.compile(r"James J. Bach Elliot Cowdin")
    p0334 = re.compile(r"(M. )?(Pierre )?J(audon|AUDON)")
    p0335 = re.compile(r"(Madame )?(Louis )?J(AUR(E|È)S|aurès)")
    p0338 = re.compile(r"Jeanne d'Arc")
    p0339 = re.compile(r"Joffre")
    p0340 = re.compile(r"((Général|Maréchal|Madame) )?Joffre")
    p0342 = re.compile(r"(Colonel )?John HAY")
    p0343 = re.compile(r"(Douglas|W.) J(ohnson|OHNSON)")
    p0344 = re.compile(r"miss Jones")
    p0345 = re.compile(r"José Matias MANZANILLA")
    p0346 = re.compile(r"(M. )?J(ouhaux|OUHAUX)")
    p0348 = re.compile(r"Jusserand")
    p0349 = re.compile(r"Kant")
    p0350 = re.compile(r"(M(.|ichel) )?KEBEDGY")
    p0351 = re.compile(r"Keller")
    p0352 = re.compile(r"M(r)?. KENNAN")
    p0353 = re.compile(r"K(eppel|EPPEL)")
    p0354 = re.compile(r"K(erensky|EMEXY)")
    p0355 = re.compile(r"Comte KERTLING")
    p0356 = re.compile(r"A.Keufer")
    p0357 = re.compile(r"M. K(lotz|LOTZ)")
    p0358 = re.compile(r"(M. )?Knox")
    p0359 = re.compile(r"(Maxime )?Ko(v|w)alewski")
    p0360 = re.compile(r"K(ronprinz|RONPRINZ)")
    p0361 = re.compile(r"Kühn")
    p0362 = re.compile(r"Commandant l'Enfant")
    p0363 = re.compile(r"(Mme.? ?)la Comtesse de Caraman Chimay")
    p0364 = re.compile(r"la Rochefoucauld")
    p0365 = re.compile(r"Vice-Présidents Amiral Lacaze")
    p0366 = re.compile(r"Lacroix")
    p0367 = re.compile(r"M. LAFOREST")
    p0368 = re.compile(r"Laloy")
    p0369 = re.compile(r"Lamartine")
    p0370 = re.compile(r"(Professeur )?L(ammasch|AMMASCH)")
    p0371 = re.compile(r"(M. )?(Christian )?(L. )?L(ange|ANGE)")
    p0372 = re.compile(r"(M. )?L(anglet|ANGLET)")
    p0373 = re.compile(r"Laplace")
    p0374 = re.compile(r"F. Larnaude")
    p0376 = re.compile(r"(Député|M.) Laroche")
    p0377 = re.compile(r"L(aubeuf|AUBEUF)")
    p0378 = re.compile(r"St(ephen|éphane) Lauzanne")
    p0379 = re.compile(r"Henri LAVEDAN")
    p0380 = re.compile(r"(M. )?(E(.|rnest) )?L(avisse|AVISSE)")
    p0381 = re.compile(r"le Caquot")
    p0382 = re.compile(r"(Madame )?(Albert )?(l|L)e Guillard")
    p0384 = re.compile(r"André Lebey")
    p0385 = re.compile(r"louis Leblois")
    p0386 = re.compile(r"(M. )?Ledoux")
    p0387 = re.compile(r"Ledoyen")
    p0388 = re.compile(r"Abbé Lemire")
    p0389 = re.compile(r"G. Lenôtre")
    p0390 = re.compile(r"Xavier Léon")
    p0393 = re.compile(r"(Victor )?L(epêcheux|EPECHEUX)")
    p0394 = re.compile(r"Leslie Mac Dill")
    p0395 = re.compile(r"(Comtesse )?Olga Leutrum")
    p0396 = re.compile(r"Raphaël( |-)Georges Lévy")
    p0397 = re.compile(r"Lewis")
    p0398 = re.compile(r"Leygues")
    p0399 = re.compile(r"M. Liard")
    p0400 = re.compile(r"((P|p)rince )?L(ichnow(e|s)k(i|y)|ICHNOWSK(I|Y))")
    p0401 = re.compile(r"Lieutenant Marchal")
    p0402 = re.compile(r"(M. )?L(l(l)?oyd|LOYD) G(eorge|EORGE)")
    p0403 = re.compile(r"Lockroy")
    p0404 = re.compile(r"M.Maurice Long")
    p0405 = re.compile(r"M. LOUBET")
    p0406 = re.compile(r"M. Loucheur")
    p0407 = re.compile(r"Louis X(VI|IV|V)?")
    p0408 = re.compile(r"Louis XIV")
    p0409 = re.compile(r"Louis XV")
    p0410 = re.compile(r"Louis XVI")
    p0411 = re.compile(r"Loustalot")
    p0412 = re.compile(r"Lovejoy")
    p0413 = re.compile(r"S(eth|ETH)( |-)L(ow|OW)")
    p0414 = re.compile(r"Lowell")
    p0415 = re.compile(r"L. Mabilleau")
    p0416 = re.compile(r"MAC DONALD")
    p0417 = re.compile(r"MACBETH")
    p0418 = re.compile(r"MACNAB")
    p0419 = re.compile(r"Maginot")
    p0420 = re.compile(r"Maigné")
    p0421 = re.compile(r"Major Geoffrey Harper Bonnell")
    p0422 = re.compile(r"Malard")
    p0423 = re.compile(r"Malicorne")
    p0424 = re.compile(r"(M. )?M(alvy|ALVY)")
    p0425 = re.compile(r"commandant Marchand")
    p0426 = re.compile(r"Miss Margaret Alexander")
    p0427 = re.compile(r"Mariani")
    p0428 = re.compile(r"Mariano B. CORNEDO")
    p0429 = re.compile(r"Marie Lapierre")
    p0430 = re.compile(r"Général Marieni")
    p0431 = re.compile(r"M. Maringer")
    p0432 = re.compile(r"Marquis de Blandford")
    p0433 = re.compile(r"Marquis de Polignac")
    p0434 = re.compile(r"(Baron )?(Edward )?Marshall( von Biberstein)?")
    p0435 = re.compile(r"Charles Martel")
    p0436 = re.compile(r"Henri( |-)Martin")
    p0437 = re.compile(r"Marx")
    p0438 = re.compile(r"René Masse")
    p0439 = re.compile(r"(Miss )?MAT(T)?HEWS")
    p0440 = re.compile(r"MAUD'HUY")
    p0441 = re.compile(r"Victor MAURTUA")
    p0442 = re.compile(r"N. Meeze")
    p0443 = re.compile(r"M. Ménard-Dorian")
    p0444 = re.compile(r"(Mme.? ?) Ménard-Dorian")
    p0445 = re.compile(r"G(.|aston) M((e|é)nier|ENIER)")
    p0446 = re.compile(r"Comte Mensdor")
    p0447 = re.compile(r"Mercellus")
    p0448 = re.compile(r"CARDINAL MERCIER")
    p0449 = re.compile(r"Daniel Mérillon")
    p0450 = re.compile(r"(Mme. )?M(ezes|EZES)")
    p0451 = re.compile(r"Michaëlis")
    p0452 = re.compile(r"André Michel")
    p0453 = re.compile(r"Henri Michel")
    p0454 = re.compile(r"Michelet")
    p0455 = re.compile(r"(M. )?M(ILIOUKOFF|il(l)?ioukoff)")
    p0456 = re.compile(r"(M. )?(A.)?M(illerand|ILLERAND)")
    p0457 = re.compile(r"Lucien MILLEVOYE")
    p0458 = re.compile(r"Albert Mirabaud")
    p0459 = re.compile(r"(colonel )?(William )?M(itchell|ITCHELL)")
    p0460 = re.compile(r"(Adrien )?Mithouard")
    p0461 = re.compile(r"(Monsieur )?(T. ?)?M(iyaoka|IYAOKA|yiaoka|iayoka|YIAOKA)")
    p0462 = re.compile(r"Moch")
    p0463 = re.compile(r"Claude Monet")
    p0464 = re.compile(r"M. R. MONETA")
    p0465 = re.compile(r"Wilfred Monod")
    p0466 = re.compile(r"(James )?Monro(ë|e)")
    p0467 = re.compile(r"Monseigneur Baudrillard")
    p0468 = re.compile(r"Morales")
    p0469 = re.compile(r"M. Morton Prince")
    p0470 = re.compile(r"(M. )?Motono")
    p0471 = re.compile(r"Mouratieff")
    p0472 = re.compile(r"(Dr. )?Mu(e)?l(l)?hon")
    p0473 = re.compile(r"Napoléon( (I|l)(er)?)?")
    p0474 = re.compile(r"Newton")
    p0475 = re.compile(r"(M. ?)?((le )?Professeur )?(O. ?)?N(ippold|IPPOLD)")
    p0476 = re.compile(r"(Général )?N(ivelle|IVELLE)")
    p0477 = re.compile(r"Lord N(orthcliffe|ORTHCLIFFE)")
    p0478 = re.compile(r"Emile NOURRY")
    p0479 = re.compile(r"M. OGIER")
    p0481 = re.compile(r"Caporal CHADWICK Oliver")
    p0483 = re.compile(r"M. ORLANDO")
    p0484 = re.compile(r"Ostwald")
    p0485 = re.compile(r"Otlet")
    p0486 = re.compile(r"Otto Weddigen")
    p0487 = re.compile(r"(M. )?(P(.|aul ))?P(ainlevé|AINLEVÉ)")
    p0488 = re.compile(r"PAÏVA")
    p0489 = re.compile(r"pasteur Abraham M. Rihbany")
    p0490 = re.compile(r"Général P(É|E)DOYA")
    p0491 = re.compile(r"Pégoud")
    p0492 = re.compile(r"Pépin le Bref")
    p0493 = re.compile(r"Général P(ercin|ERCIN)")
    p0494 = re.compile(r"(M. )?Raoul P(ERET|éret)")
    p0495 = re.compile(r"(Edmond|Edouard) Perrier")
    p0496 = re.compile(r"(Général )?(Maréchal )?P(ershing|ERShING)")
    p0497 = re.compile(r"(Général|Maréchal) Pétain")
    p0498 = re.compile(r"M(ademoiselle|lles|lle.?) P(eylade|EYLADE)")
    p0499 = re.compile(r"(M. )?(S(.|téphane) )?P(ichon|ICHON)")
    p0500 = re.compile(r"Pinot")
    p0501 = re.compile(r"M. Piou")
    p0503 = re.compile(r"(M(.|onsieur) )?(Président )?P(oincaré|OINCAR(É|E))")
    p0504 = re.compile(r"E. Poisson")
    p0505 = re.compile(r"Ponce Pilate")
    p0506 = re.compile(r"Poncet")
    p0508 = re.compile(r"Mlle. Port")
    p0509 = re.compile(r"Potié")
    p0510 = re.compile(r"Francis de Pressensé")
    p0511 = re.compile(r"Marcel P(révost|REVOST)")
    p0512 = re.compile(r"Prince Eitel")
    p0513 = re.compile(r"Prince Sixte de Bourbon")
    p0515 = re.compile(r"(M. )?(J(.|ules) ?)P(rudhommeaux|RUDHOMMEAUX)")
    p0516 = re.compile(r"Ptolémée")
    p0517 = re.compile(r"(Madame )?(Mme.? ?)?(J.L. )?(P|B)(uech|UECH)")
    p0518 = re.compile(r"P(yrrhus|YRRHUS)")
    p0519 = re.compile(r"Quesada Juvier")
    p0520 = re.compile(r"(Dr|M). Quidde")
    p0521 = re.compile(r"Charles Quint")
    p0522 = re.compile(r"Rabelais")
    p0523 = re.compile(r"G(énéral|ÉNÉRAL) R(adiguet|ADIGUET)")
    p0524 = re.compile(r"Raiberti")
    p0525 = re.compile(r"Raspoutine")
    p0526 = re.compile(r"C(ommandant|OMMANDANT)( Albert C.)? READ")
    p0527 = re.compile(r"Edgar Quinet")
    p0528 = re.compile(r"Reine Victoria")
    p0529 = re.compile(r"Renan")
    p0530 = re.compile(r"(P(.|ierre) )?R(enaudel|ENAUDEL)")
    p0531 = re.compile(r"(M. )?(L(.|OUIS|ouis) )?R(enault|ENAULT)")
    p0532 = re.compile(r"RERENOFF")
    p0533 = re.compile(r"(Emile )?Reymond")
    p0534 = re.compile(r"Reynolds")
    p0535 = re.compile(r"(M. )?REYSS")
    p0536 = re.compile(r"(M. )?(Madame )?(A(.|lexandre) )?R(IBOT|ibot)")
    p0538 = re.compile(r"Richemond")
    p0539 = re.compile(r"(Charles )?R(ichet|ICHET)")
    p0540 = re.compile(r"Gustave Rivet")
    p0541 = re.compile(r"(M.|Henri) Robelin")
    p0542 = re.compile(r"Henri Robert")
    p0543 = re.compile(r"(Lord )?Robert Cecil")
    p0544 = re.compile(r"Albert Robin")
    p0545 = re.compile(r"(Mlle.? )ROCH")
    p0546 = re.compile(r"Rochefoucault")
    p0547 = re.compile(r"R(odin|ODIN)")
    p0548 = re.compile(r"Roi Alphonse")
    p0549 = re.compile(r"Roi Edouard")
    p0550 = re.compile(r"A.Roll")
    p0551 = re.compile(r"Romanoff")
    p0552 = re.compile(r"Romney")
    p0553 = re.compile(r"(M. )?(P(RÉSIDENT|résident) )?(Théodore )?R(oosevelt|OOSEVELT)")
    p0554 = re.compile(r"(M(.|r) )?(E(.|lihu) )?R(oot|OOT)")
    p0555 = re.compile(r"Rostand")
    p0556 = re.compile(r"Alfred Roth")
    p0557 = re.compile(r"Rotschild")
    p0558 = re.compile(r"(Jean-Jacques )?(J.J.)?R(ousseau|OUSSEAU)")
    p0559 = re.compile(r"Henri Rousselle")
    p0560 = re.compile(r"Dr. G. Roux")
    p0561 = re.compile(r"Andrew Ruel")
    p0563 = re.compile(r"(Théodore )?R(uyssen|UYSSEN)")
    p0564 = re.compile(r"S. E. le Cardinal")
    p0565 = re.compile(r"Melle Sainte-Marie")
    p0566 = re.compile(r"Lord Salisbury")
    p0567 = re.compile(r"(Professeur )?(S. )?S(alvemini|ALVEMINI)")
    p0568 = re.compile(r"Marc SANGNIER")
    p0569 = re.compile(r"(Général )?(M. )?(Pedro )?S(angro(s)?|ANGRO(S)?) (d|D)(e|E|i|I) O(lano|LANO)")
    p0570 = re.compile(r"Santos-Dumont")
    p0571 = re.compile(r"L(.|ouis) S(ARRUT|arrut)")
    p0572 = re.compile(r"Jules Sauerwein")
    p0573 = re.compile(r"Lord SAUNCEFOTE")
    p0574 = re.compile(r"SCHEIDEIMANN")
    p0575 = re.compile(r"Schiller")
    p0576 = re.compile(r"Schneider( du Creuzot)?")
    p0577 = re.compile(r"Schoelscher")
    p0578 = re.compile(r"Schoen")
    p0579 = re.compile(r"M. W. Schucking")
    p0580 = re.compile(r"Schum(m)?ann")
    p0581 = re.compile(r"(G(.|abriel) )?S(éailles|EAILLES)")
    p0582 = re.compile(r"Général S(ébert|EBERT)")
    p0583 = re.compile(r"Sedgwick Berend")
    p0584 = re.compile(r"(M(. ?|arcel ))?S(embat|EMBAT)")
    p0585 = re.compile(r"(Colonel )?(John )?(Stephan )?SEWELL")
    p0586 = re.compile(r"M(.|onsieur) ?S(harp|HARP)")
    p0587 = re.compile(r"Lord Shaw")
    p0588 = re.compile(r"T. Shotwell")
    p0589 = re.compile(r"Sidi Brahim")
    p0590 = re.compile(r"(Mme.? ?)?(J(.|ules ))?S(iegfried|IEGFRIED)")
    p0592 = re.compile(r"Siraudin")
    p0593 = re.compile(r"Sisyphe")
    p0594 = re.compile(r"Smith")
    p0595 = re.compile(r"Solvay")
    p0596 = re.compile(r"Sopwith")
    p0597 = re.compile(r"(Pasteur )?S(oulié|OULIÉ)")
    p0598 = re.compile(r"Spencer")
    p0599 = re.compile(r"STAAL")
    p0600 = re.compile(r"Staehling")
    p0601 = re.compile(r"M.E.Stagg Whitin")
    p0602 = re.compile(r"S(teeg|TEEG)")
    p0603 = re.compile(r"Stendhal")
    p0604 = re.compile(r"(M(.|r) )?(O(.|scar) )?(S. )?S(traus(s)?|TRAUS(S)?)")
    p0605 = re.compile(r"Mr. STUNNE")
    p0606 = re.compile(r"Surcouf")
    p0607 = re.compile(r"(M(.|r) )?(W. )?T(aft|AFT)")
    p0608 = re.compile(r"Taplow")
    p0609 = re.compile(r"(André )?T(ardieu|ARDIEU)")
    p0610 = re.compile(r"Général Targe")
    p0611 = re.compile(r"(M. )?(G(.|ustave) )?T(éry|ERY)")
    p0612 = re.compile(r"William Thaw")
    p0613 = re.compile(r"E. Théry")
    p0614 = re.compile(r"M. J. Thierry")
    p0615 = re.compile(r"(M. )?T(hiers|HIERS)")
    p0616 = re.compile(r"A(.|(l|L)bert) T(homas|HOMAS)")
    p0617 = re.compile(r"Tiepolo")
    p0618 = re.compile(r"(Amiral )?Tirpitz")
    p0619 = re.compile(r"Tolstoï")
    p0620 = re.compile(r"Tornielli")
    p0621 = re.compile(r"Président TOZES")
    p0623 = re.compile(r"(S. E. )?L(ou|OU) T(sen(g|c)|SEN(G|C)) T(siang|SIANG)")
    p0624 = re.compile(r"M. E(.|edward) T(UCK|uck)")
    p0625 = re.compile(r"Tuffier")
    p0627 = re.compile(r"Tzar Ferdinand")
    p0628 = re.compile(r"Alberto ULLOA")
    p0630 = re.compile(r"M. Valdeck-Rousseau")
    p0631 = re.compile(r"Vallé")
    p0632 = re.compile(r"(M. )?(V|v)an der Does de (V|W)illebois")
    p0633 = re.compile(r"M. VAN OVERBERGE")
    p0634 = re.compile(r"V(andervelde|ANDERVELDE)")
    p0635 = re.compile(r"Vaschalde")
    p0636 = re.compile(r"(M. )?V(ENIZELOS|enizelos)")
    p0637 = re.compile(r"(A(bbé|BBÉ) )?(V|W)(etterlé|ETTERLÉ)")
    p0639 = re.compile(r"Adolfo VILLAGARCIA")
    p0640 = re.compile(r"Villain")
    p0641 = re.compile(r"Vicente VILLARAN")
    p0642 = re.compile(r"Daniel Vincent")
    p0643 = re.compile(r"Vindex")
    p0644 = re.compile(r"(M. )?(R(.|ené) )?V(iviani|IVIANI)")
    p0645 = re.compile(r"Voltaire")
    p0646 = re.compile(r"(PASTEUR )?(Richard )?(w|W)(agner|AGNER)")
    p0647 = re.compile(r"(M. )?(Madame )?(Hugh C. )?(H. )?WALLACE")
    p0648 = re.compile(r"M. WALSH")
    p0649 = re.compile(r"(M. )?Whit(h)?ney Warren")
    p0650 = re.compile(r"Lord W(eardale|EARDALE)")
    p0651 = re.compile(r"Weill")
    p0652 = re.compile(r"Sir William WEIR")
    p0653 = re.compile(r"(M. )?(A(.|ndré) )?W(EISS|eiss)")
    p0654 = re.compile(r"(P(résident|RÉSIDENT) )?W(heeler|HEELER)")
    p0655 = re.compile(r"Henry W(hite|HITE)")
    p0656 = re.compile(r"William Wallace Lyons")
    p0657 = re.compile(r"M. WYTHE WILLIAMS")
    p0658 = re.compile(r"(Madame )?(M. )?((le )?(p|P)(résident|R(É|E)SIDENT) )?W(ilson|ILSON)")
    p0660 = re.compile(r"(Wilbur )?Wright")
    p0661 = re.compile(r"Xavier de Maistre")
    p0662 = re.compile(r"Zola")
    p0663 = re.compile(r"(Professeur )?Z(ORN|orn)")
    p0664 = re.compile(r"Liebnecht")


    #This series of statements contains the encoding for the persons from the corpus
    text = re.sub(p0001, r'<persName ref="#p0001" type="pec">\g<0></persName>', text)
    text = re.sub(p0002, r'<persName ref="#p0002" type="pec">\g<0></persName>', text)
    text = re.sub(p0003, r'<persName ref="#p0003" type="pec">\g<0></persName>', text)
    text = re.sub(p0004, r'<persName ref="#p0004" type="pec">\g<0></persName>', text)
    text = re.sub(p0005, r'<persName ref="#p0005" type="pec">\g<0></persName>', text)
    text = re.sub(p0006, r'<persName ref="#p0006" type="pec">\g<0></persName>', text)
    text = re.sub(p0007, r'<persName ref="#p0007" type="pec">\g<0></persName>', text)
    text = re.sub(p0008, r'<persName ref="#p0008" type="pec">\g<0></persName>', text)
    text = re.sub(p0009, r'<persName ref="#p0009" type="pec">\g<0></persName>', text)
    text = re.sub(p0010, r'<persName ref="#p0010" type="pec">\g<0></persName>', text)
    text = re.sub(p0011, r'<persName ref="#p0011" type="pec">\g<0></persName>', text)
    text = re.sub(p0012, r'<persName ref="#p0012" type="pec">\g<0></persName>', text)
    text = re.sub(p0013, r'<persName ref="#p0013" type="pec">\g<0></persName>', text)
    text = re.sub(p0014, r'<persName ref="#p0014" type="pec">\g<0></persName>', text)
    text = re.sub(p0015, r'<persName ref="#p0015" type="pec">\g<0></persName>', text)
    text = re.sub(p0016, r'<persName ref="#p0016" type="pec">\g<0></persName>', text)
    text = re.sub(p0017, r'<persName ref="#p0017" type="pec">\g<0></persName>', text)
    text = re.sub(p0018, r'<persName ref="#p0018" type="pec">\g<0></persName>', text)
    text = re.sub(p0019, r'<persName ref="#p0019" type="pec">\g<0></persName>', text)
    text = re.sub(p0020, r'<persName ref="#p0020" type="pec">\g<0></persName>', text)
    text = re.sub(p0021, r'<persName ref="#p0021" type="pec">\g<0></persName>', text)
    text = re.sub(p0022, r'<persName ref="#p0022" type="pec">\g<0></persName>', text)
    text = re.sub(p0023, r'<persName ref="#p0023" type="pec">\g<0></persName>', text)
    text = re.sub(p0024, r'<persName ref="#p0024" type="pec">\g<0></persName>', text)
    text = re.sub(p0025, r'<persName ref="#p0025" type="pec">\g<0></persName>', text)
    text = re.sub(p0026, r'<persName ref="#p0026" type="pec">\g<0></persName>', text)
    text = re.sub(p0027, r'<persName ref="#p0027" type="pec">\g<0></persName>', text)
    text = re.sub(p0028, r'<persName ref="#p0028" type="pec">\g<0></persName>', text)
    text = re.sub(p0029, r'<persName ref="#p0029" type="pec">\g<0></persName>', text)
    text = re.sub(p0030, r'<persName ref="#p0030" type="pec">\g<0></persName>', text)
    text = re.sub(p0031, r'<persName ref="#p0031" type="pec">\g<0></persName>', text)
    text = re.sub(p0032, r'<persName ref="#p0032" type="pec">\g<0></persName>', text)
    text = re.sub(p0033, r'<persName ref="#p0033" type="pec">\g<0></persName>', text)
    text = re.sub(p0034, r'<persName ref="#p0034" type="pec">\g<0></persName>', text)
    text = re.sub(p0035, r'<persName ref="#p0035" type="pec">\g<0></persName>', text)
    text = re.sub(p0036, r'<persName ref="#p0036" type="pec">\g<0></persName>', text)
    text = re.sub(p0037, r'<persName ref="#p0037" type="pec">\g<0></persName>', text)
    text = re.sub(p0038, r'<persName ref="#p0038" type="pec">\g<0></persName>', text)
    text = re.sub(p0039, r'<persName ref="#p0039" type="pec">\g<0></persName>', text)
    text = re.sub(p0040, r'<persName ref="#p0040" type="pec">\g<0></persName>', text)
    text = re.sub(p0041, r'<persName ref="#p0041" type="pec">\g<0></persName>', text)
    text = re.sub(p0042, r'<persName ref="#p0042" type="pec">\g<0></persName>', text)
    text = re.sub(p0043, r'<persName ref="#p0043" type="pec">\g<0></persName>', text)
    text = re.sub(p0044, r'<persName ref="#p0044" type="pec">\g<0></persName>', text)
    text = re.sub(p0045, r'<persName ref="#p0045" type="pec">\g<0></persName>', text)
    text = re.sub(p0046, r'<persName ref="#p0046" type="pec">\g<0></persName>', text)
    text = re.sub(p0047, r'<persName ref="#p0047" type="pec">\g<0></persName>', text)
    text = re.sub(p0048, r'<persName ref="#p0048" type="pec">\g<0></persName>', text)
    text = re.sub(p0049, r'<persName ref="#p0049" type="pec">\g<0></persName>', text)
    text = re.sub(p0050, r'<persName ref="#p0050" type="pec">\g<0></persName>', text)
    text = re.sub(p0051, r'<persName ref="#p0051" type="pec">\g<0></persName>', text)
    text = re.sub(p0052, r'<persName ref="#p0052" type="pec">\g<0></persName>', text)
    text = re.sub(p0053, r'<persName ref="#p0053" type="pec">\g<0></persName>', text)
    text = re.sub(p0054, r'<persName ref="#p0054" type="pec">\g<0></persName>', text)
    text = re.sub(p0055, r'<persName ref="#p0055" type="pec">\g<0></persName>', text)
    text = re.sub(p0056, r'<persName ref="#p0056" type="pec">\g<0></persName>', text)
    text = re.sub(p0057, r'<persName ref="#p0057" type="pec">\g<0></persName>', text)
    text = re.sub(p0058, r'<persName ref="#p0058" type="pec">\g<0></persName>', text)
    text = re.sub(p0059, r'<persName ref="#p0059" type="pec">\g<0></persName>', text)
    text = re.sub(p0060, r'<persName ref="#p0060" type="pec">\g<0></persName>', text)
    text = re.sub(p0061, r'<persName ref="#p0061" type="pec">\g<0></persName>', text)
    text = re.sub(p0062, r'<persName ref="#p0062" type="pec">\g<0></persName>', text)
    text = re.sub(p0063, r'<persName ref="#p0063" type="pec">\g<0></persName>', text)
    text = re.sub(p0065, r'<persName ref="#p0065" type="pec">\g<0></persName>', text)
    text = re.sub(p0066, r'<persName ref="#p0066" type="pec">\g<0></persName>', text)
    text = re.sub(p0067, r'<persName ref="#p0067" type="pec">\g<0></persName>', text)
    text = re.sub(p0068, r'<persName ref="#p0068" type="pec">\g<0></persName>', text)
    text = re.sub(p0069, r'<persName ref="#p0069" type="pec">\g<0></persName>', text)
    text = re.sub(p0070, r'<persName ref="#p0070" type="pec">\g<0></persName>', text)
    text = re.sub(p0071, r'<persName ref="#p0071" type="pec">\g<0></persName>', text)
    text = re.sub(p0072, r'<persName ref="#p0072" type="pec">\g<0></persName>', text)
    text = re.sub(p0073, r'<persName ref="#p0073" type="pec">\g<0></persName>', text)
    text = re.sub(p0074, r'<persName ref="#p0074" type="pec">\g<0></persName>', text)
    text = re.sub(p0075, r'<persName ref="#p0075" type="pec">\g<0></persName>', text)
    text = re.sub(p0076, r'<persName ref="#p0076" type="pec">\g<0></persName>', text)
    text = re.sub(p0078, r'<persName ref="#p0078" type="pec">\g<0></persName>', text)
    text = re.sub(p0079, r'<persName ref="#p0079" type="pec">\g<0></persName>', text)
    text = re.sub(p0080, r'<persName ref="#p0080" type="pec">\g<0></persName>', text)
    text = re.sub(p0081, r'<persName ref="#p0081" type="pec">\g<0></persName>', text)
    text = re.sub(p0082, r'<persName ref="#p0082" type="pec">\g<0></persName>', text)
    text = re.sub(p0083, r'<persName ref="#p0083" type="pec">\g<0></persName>', text)
    text = re.sub(p0084, r'<persName ref="#p0084" type="pec">\g<0></persName>', text)
    text = re.sub(p0085, r'<persName ref="#p0085" type="pec">\g<0></persName>', text)
    text = re.sub(p0087, r'<persName ref="#p0087" type="pec">\g<0></persName>', text)
    text = re.sub(p0088, r'<persName ref="#p0088" type="pec">\g<0></persName>', text)
    text = re.sub(p0089, r'<persName ref="#p0089" type="pec">\g<0></persName>', text)
    text = re.sub(p0090, r'<persName ref="#p0090" type="pec">\g<0></persName>', text)
    text = re.sub(p0091, r'<persName ref="#p0091" type="pec">\g<0></persName>', text)
    text = re.sub(p0092, r'<persName ref="#p0092" type="pec">\g<0></persName>', text)
    text = re.sub(p0093, r'<persName ref="#p0093" type="pec">\g<0></persName>', text)
    text = re.sub(p0094, r'<persName ref="#p0094" type="pec">\g<0></persName>', text)
    text = re.sub(p0095, r'<persName ref="#p0095" type="pec">\g<0></persName>', text)
    text = re.sub(p0096, r'<persName ref="#p0096" type="pec">\g<0></persName>', text)
    text = re.sub(p0097, r'<persName ref="#p0097" type="pec">\g<0></persName>', text)
    text = re.sub(p0099, r'<persName ref="#p0099" type="pec">\g<0></persName>', text)
    text = re.sub(p0100, r'<persName ref="#p0100" type="pec">\g<0></persName>', text)
    text = re.sub(p0101, r'<persName ref="#p0101" type="pec">\g<0></persName>', text)
    text = re.sub(p0103, r'<persName ref="#p0103" type="pec">\g<0></persName>', text)
    text = re.sub(p0104, r'<persName ref="#p0104" type="pec">\g<0></persName>', text)
    text = re.sub(p0105, r'<persName ref="#p0105" type="pec">\g<0></persName>', text)
    text = re.sub(p0106, r'<persName ref="#p0106" type="pec">\g<0></persName>', text)
    text = re.sub(p0107, r'<persName ref="#p0107" type="pec">\g<0></persName>', text)
    text = re.sub(p0108, r'<persName ref="#p0108" type="pec">\g<0></persName>', text)
    text = re.sub(p0109, r'<persName ref="#p0109" type="pec">\g<0></persName>', text)
    text = re.sub(p0110, r'<persName ref="#p0110" type="pec">\g<0></persName>', text)
    text = re.sub(p0111, r'<persName ref="#p0111" type="pec">\g<0></persName>', text)
    text = re.sub(p0113, r'<persName ref="#p0113" type="pec">\g<0></persName>', text)
    text = re.sub(p0115, r'<persName ref="#p0115" type="pec">\g<0></persName>', text)
    text = re.sub(p0116, r'<persName ref="#p0116" type="pec">\g<0></persName>', text)
    text = re.sub(p0117, r'<persName ref="#p0117" type="pec">\g<0></persName>', text)
    text = re.sub(p0118, r'<persName ref="#p0118" type="pec">\g<0></persName>', text)
    text = re.sub(p0119, r'<persName ref="#p0119" type="pec">\g<0></persName>', text)
    text = re.sub(p0120, r'<persName ref="#p0120" type="pec">\g<0></persName>', text)
    text = re.sub(p0121, r'<persName ref="#p0121" type="pec">\g<0></persName>', text)
    text = re.sub(p0122, r'<persName ref="#p0122" type="pec">\g<0></persName>', text)
    text = re.sub(p0123, r'<persName ref="#p0123" type="pec">\g<0></persName>', text)
    text = re.sub(p0125, r'<persName ref="#p0125" type="pec">\g<0></persName>', text)
    text = re.sub(p0126, r'<persName ref="#p0126" type="pec">\g<0></persName>', text)
    text = re.sub(p0127, r'<persName ref="#p0127" type="pec">\g<0></persName>', text)
    text = re.sub(p0128, r'<persName ref="#p0128" type="pec">\g<0></persName>', text)
    text = re.sub(p0129, r'<persName ref="#p0129" type="pec">\g<0></persName>', text)
    text = re.sub(p0130, r'<persName ref="#p0130" type="pec">\g<0></persName>', text)
    text = re.sub(p0131, r'<persName ref="#p0131" type="pec">\g<0></persName>', text)
    text = re.sub(p0132, r'<persName ref="#p0132" type="pec">\g<0></persName>', text)
    text = re.sub(p0133, r'<persName ref="#p0133" type="pec">\g<0></persName>', text)
    text = re.sub(p0134, r'<persName ref="#p0134" type="pec">\g<0></persName>', text)
    text = re.sub(p0135, r'<persName ref="#p0135" type="pec">\g<0></persName>', text)
    text = re.sub(p0136, r'<persName ref="#p0136" type="pec">\g<0></persName>', text)
    text = re.sub(p0138, r'<persName ref="#p0138" type="pec">\g<0></persName>', text)
    text = re.sub(p0139, r'<persName ref="#p0139" type="pec">\g<0></persName>', text)
    text = re.sub(p0140, r'<persName ref="#p0140" type="pec">\g<0></persName>', text)
    text = re.sub(p0141, r'<persName ref="#p0141" type="pec">\g<0></persName>', text)
    text = re.sub(p0142, r'<persName ref="#p0142" type="pec">\g<0></persName>', text)
    text = re.sub(p0143, r'<persName ref="#p0143" type="pec">\g<0></persName>', text)
    text = re.sub(p0144, r'<persName ref="#p0144" type="pec">\g<0></persName>', text)
    text = re.sub(p0146, r'<persName ref="#p0146" type="pec">\g<0></persName>', text)
    text = re.sub(p0147, r'<persName ref="#p0147" type="pec">\g<0></persName>', text)
    text = re.sub(p0148, r'<persName ref="#p0148" type="pec">\g<0></persName>', text)
    text = re.sub(p0149, r'<persName ref="#p0149" type="pec">\g<0></persName>', text)
    text = re.sub(p0150, r'<persName ref="#p0150" type="pec">\g<0></persName>', text)
    text = re.sub(p0151, r'<persName ref="#p0151" type="pec">\g<0></persName>', text)
    text = re.sub(p0152, r'<persName ref="#p0152" type="pec">\g<0></persName>', text)
    text = re.sub(p0153, r'<persName ref="#p0153" type="pec">\g<0></persName>', text)
    text = re.sub(p0154, r'<persName ref="#p0154" type="pec">\g<0></persName>', text)
    text = re.sub(p0155, r'<persName ref="#p0155" type="pec">\g<0></persName>', text)
    text = re.sub(p0156, r'<persName ref="#p0156" type="pec">\g<0></persName>', text)
    text = re.sub(p0157, r'<persName ref="#p0157" type="pec">\g<0></persName>', text)
    text = re.sub(p0158, r'<persName ref="#p0158" type="pec">\g<0></persName>', text)
    text = re.sub(p0159, r'<persName ref="#p0159" type="pec">\g<0></persName>', text)
    text = re.sub(p0161, r'<persName ref="#p0161" type="pec">\g<0></persName>', text)
    text = re.sub(p0162, r'<persName ref="#p0162" type="pec">\g<0></persName>', text)
    text = re.sub(p0163, r'<persName ref="#p0163" type="pec">\g<0></persName>', text)
    text = re.sub(p0164, r'<persName ref="#p0164" type="pec">\g<0></persName>', text)
    text = re.sub(p0165, r'<persName ref="#p0165" type="pec">\g<0></persName>', text)
    text = re.sub(p0166, r'<persName ref="#p0166" type="pec">\g<0></persName>', text)
    text = re.sub(p0167, r'<persName ref="#p0167" type="pec">\g<0></persName>', text)
    text = re.sub(p0168, r'<persName ref="#p0168" type="pec">\g<0></persName>', text)
    text = re.sub(p0169, r'<persName ref="#p0169" type="pec">\g<0></persName>', text)
    text = re.sub(p0170, r'<persName ref="#p0170" type="pec">\g<0></persName>', text)
    text = re.sub(p0171, r'<persName ref="#p0171" type="pec">\g<0></persName>', text)
    text = re.sub(p0172, r'<persName ref="#p0172" type="pec">\g<0></persName>', text)
    text = re.sub(p0173, r'<persName ref="#p0173" type="pec">\g<0></persName>', text)
    text = re.sub(p0174, r'<persName ref="#p0174" type="pec">\g<0></persName>', text)
    text = re.sub(p0175, r'<persName ref="#p0175" type="pec">\g<0></persName>', text)
    text = re.sub(p0176, r'<persName ref="#p0176" type="pec">\g<0></persName>', text)
    text = re.sub(p0177, r'<persName ref="#p0177" type="pec">\g<0></persName>', text)
    text = re.sub(p0178, r'<persName ref="#p0178" type="pec">\g<0></persName>', text)
    text = re.sub(p0179, r'<persName ref="#p0179" type="pec">\g<0></persName>', text)
    text = re.sub(p0180, r'<persName ref="#p0180" type="pec">\g<0></persName>', text)
    text = re.sub(p0181, r'<persName ref="#p0181" type="pec">\g<0></persName>', text)
    text = re.sub(p0182, r'<persName ref="" type="pec">\g<0></persName>', text)
    text = re.sub(p0183, r'<persName ref="#p0183" type="pec">\g<0></persName>', text)
    text = re.sub(p0184, r'<persName ref="#p0184" type="pec">\g<0></persName>', text)
    text = re.sub(p0185, r'<persName ref="#p0185" type="pec">\g<0></persName>', text)
    text = re.sub(p0186, r'<persName ref="#p0186" type="pec">\g<0></persName>', text)
    text = re.sub(p0187, r'<persName ref="#p0187" type="pec">\g<0></persName>', text)
    text = re.sub(p0188, r'<persName ref="#p0188" type="pec">\g<0></persName>', text)
    text = re.sub(p0189, r'<persName ref="#p0189" type="pec">\g<0></persName>', text)
    text = re.sub(p0190, r'<persName ref="#p0190" type="pec">\g<0></persName>', text)
    text = re.sub(p0191, r'<persName ref="#p0191" type="pec">\g<0></persName>', text)
    text = re.sub(p0192, r'<persName ref="#p0192" type="pec">\g<0></persName>', text)
    text = re.sub(p0193, r'<persName ref="#p0193" type="pec">\g<0></persName>', text)
    text = re.sub(p0194, r'<persName ref="#p0194" type="pec">\g<0></persName>', text)
    text = re.sub(p0195, r'<persName ref="#p0195" type="pec">\g<0></persName>', text)
    text = re.sub(p0196, r'<persName ref="#p0196" type="pec">\g<0></persName>', text)
    text = re.sub(p0197, r'<persName ref="#p0197" type="pec">\g<0></persName>', text)
    text = re.sub(p0198, r'<persName ref="#p0198" type="pec">\g<0></persName>', text)
    text = re.sub(p0199, r'<persName ref="#p0199" type="pec">\g<0></persName>', text)
    text = re.sub(p0200, r'<persName ref="#p0200" type="pec">\g<0></persName>', text)
    text = re.sub(p0201, r'<persName ref="#p0201" type="pec">\g<0></persName>', text)
    text = re.sub(p0202, r'<persName ref="#p0202" type="pec">\g<0></persName>', text)
    text = re.sub(p0203, r'<persName ref="#p0203" type="pec">\g<0></persName>', text)
    text = re.sub(p0204, r'<persName ref="#p0204" type="pec">\g<0></persName>', text)
    text = re.sub(p0205, r'<persName ref="#p0205" type="pec">\g<0></persName>', text)
    text = re.sub(p0206, r'<persName ref="#p0206" type="pec">\g<0></persName>', text)
    text = re.sub(p0207, r'<persName ref="#p0207" type="pec">\g<0></persName>', text)
    text = re.sub(p0208, r'<persName ref="#p0208" type="pec">\g<0></persName>', text)
    text = re.sub(p0209, r'<persName ref="#p0209" type="pec">\g<0></persName>', text)
    text = re.sub(p0210, r'<persName ref="#p0210" type="pec">\g<0></persName>', text)
    text = re.sub(p0211, r'<persName ref="#p0211" type="pec">\g<0></persName>', text)
    text = re.sub(p0212, r'<persName ref="#p0212" type="pec">\g<0></persName>', text)
    text = re.sub(p0213, r'<persName ref="#p0213" type="pec">\g<0></persName>', text)
    text = re.sub(p0214, r'<persName ref="#p0214" type="pec">\g<0></persName>', text)
    text = re.sub(p0215, r'<persName ref="#p0215" type="pec">\g<0></persName>', text)
    text = re.sub(p0216, r'<persName ref="#p0216" type="pec">\g<0></persName>', text)
    text = re.sub(p0217, r'<persName ref="#p0217" type="pec">\g<0></persName>', text)
    text = re.sub(p0218, r'<persName ref="#p0218" type="pec">\g<0></persName>', text)
    text = re.sub(p0219, r'<persName ref="#p0219" type="pec">\g<0></persName>', text)
    text = re.sub(p0220, r'<persName ref="#p0220" type="pec">\g<0></persName>', text)
    text = re.sub(p0221, r'<persName ref="#p0221" type="pec">\g<0></persName>', text)
    text = re.sub(p0222, r'<persName ref="#p0222" type="pec">\g<0></persName>', text)
    text = re.sub(p0224, r'<persName ref="#p0224" type="pec">\g<0></persName>', text)
    text = re.sub(p0225, r'<persName ref="#p0225" type="pec">\g<0></persName>', text)
    text = re.sub(p0226, r'<persName ref="#p0226" type="pec">\g<0></persName>', text)
    text = re.sub(p0227, r'<persName ref="#p0227" type="pec">\g<0></persName>', text)
    text = re.sub(p0229, r'<persName ref="#p0229" type="pec">\g<0></persName>', text)
    text = re.sub(p0230, r'<persName ref="#p0230" type="pec">\g<0></persName>', text)
    text = re.sub(p0231, r'<persName ref="#p0231" type="pec">\g<0></persName>', text)
    text = re.sub(p0232, r'<persName ref="#p0232" type="pec">\g<0></persName>', text)
    text = re.sub(p0233, r'<persName ref="#p0233" type="pec">\g<0></persName>', text)
    text = re.sub(p0234, r'<persName ref="#p0234" type="pec">\g<0></persName>', text)
    text = re.sub(p0235, r'<persName ref="#p0235" type="pec">\g<0></persName>', text)
    text = re.sub(p0236, r'<persName ref="#p0236" type="pec">\g<0></persName>', text)
    text = re.sub(p0237, r'<persName ref="#p0237" type="pec">\g<0></persName>', text)
    text = re.sub(p0238, r'<persName ref="#p0238" type="pec">\g<0></persName>', text)
    text = re.sub(p0239, r'<persName ref="#p0239" type="pec">\g<0></persName>', text)
    text = re.sub(p0240, r'<persName ref="#p0240" type="pec">\g<0></persName>', text)
    text = re.sub(p0241, r'<persName ref="#p0241" type="pec">\g<0></persName>', text)
    text = re.sub(p0242, r'<persName ref="#p0242" type="pec">\g<0></persName>', text)
    text = re.sub(p0243, r'<persName ref="#p0243" type="pec">\g<0></persName>', text)
    text = re.sub(p0244, r'<persName ref="#p0244" type="pec">\g<0></persName>', text)
    text = re.sub(p0245, r'<persName ref="#p0245" type="pec">\g<0></persName>', text)
    text = re.sub(p0246, r'<persName ref="#p0246" type="pec">\g<0></persName>', text)
    text = re.sub(p0247, r'<persName ref="#p0247" type="pec">\g<0></persName>', text)
    text = re.sub(p0248, r'<persName ref="#p0248" type="pec">\g<0></persName>', text)
    text = re.sub(p0249, r'<persName ref="#p0249" type="pec">\g<0></persName>', text)
    text = re.sub(p0250, r'<persName ref="#p0250" type="pec">\g<0></persName>', text)
    text = re.sub(p0251, r'<persName ref="#p0251" type="pec">\g<0></persName>', text)
    text = re.sub(p0252, r'<persName ref="#p0252" type="pec">\g<0></persName>', text)
    text = re.sub(p0253, r'<persName ref="#p0253" type="pec">\g<0></persName>', text)
    text = re.sub(p0254, r'<persName ref="#p0254" type="pec">\g<0></persName>', text)
    text = re.sub(p0255, r'<persName ref="#p0255" type="pec">\g<0></persName>', text)
    text = re.sub(p0256, r'<persName ref="#p0256" type="pec">\g<0></persName>', text)
    text = re.sub(p0257, r'<persName ref="#p0257" type="pec">\g<0></persName>', text)
    text = re.sub(p0258, r'<persName ref="#p0258" type="pec">\g<0></persName>', text)
    text = re.sub(p0259, r'<persName ref="#p0259" type="pec">\g<0></persName>', text)
    text = re.sub(p0260, r'<persName ref="#p0260" type="pec">\g<0></persName>', text)
    text = re.sub(p0261, r'<persName ref="#p0261" type="pec">\g<0></persName>', text)
    text = re.sub(p0262, r'<persName ref="#p0262" type="pec">\g<0></persName>', text)
    text = re.sub(p0263, r'<persName ref="#p0263" type="pec">\g<0></persName>', text)
    text = re.sub(p0265, r'<persName ref="#p0265" type="pec">\g<0></persName>', text)
    text = re.sub(p0266, r'<persName ref="#p0266" type="pec">\g<0></persName>', text)
    text = re.sub(p0267, r'<persName ref="#p0267" type="pec">\g<0></persName>', text)
    text = re.sub(p0268, r'<persName ref="#p0268" type="pec">\g<0></persName>', text)
    text = re.sub(p0269, r'<persName ref="#p0269" type="pec">\g<0></persName>', text)
    text = re.sub(p0270, r'<persName ref="#p0270" type="pec">\g<0></persName>', text)
    text = re.sub(p0271, r'<persName ref="#p0271" type="pec">\g<0></persName>', text)
    text = re.sub(p0272, r'<persName ref="#p0272" type="pec">\g<0></persName>', text)
    text = re.sub(p0273, r'<persName ref="#p0273" type="pec">\g<0></persName>', text)
    text = re.sub(p0274, r'<persName ref="#p0274" type="pec">\g<0></persName>', text)
    text = re.sub(p0275, r'<persName ref="#p0275" type="pec">\g<0></persName>', text)
    text = re.sub(p0276, r'<persName ref="#p0276" type="pec">\g<0></persName>', text)
    text = re.sub(p0277, r'<persName ref="#p0277" type="pec">\g<0></persName>', text)
    text = re.sub(p0278, r'<persName ref="#p0278" type="pec">\g<0></persName>', text)
    text = re.sub(p0279, r'<persName ref="#p0279" type="pec">\g<0></persName>', text)
    text = re.sub(p0280, r'<persName ref="#p0280" type="pec">\g<0></persName>', text)
    text = re.sub(p0281, r'<persName ref="#p0281" type="pec">\g<0></persName>', text)
    text = re.sub(p0282, r'<persName ref="#p0282" type="pec">\g<0></persName>', text)
    text = re.sub(p0283, r'<persName ref="#p0283" type="pec">\g<0></persName>', text)
    text = re.sub(p0284, r'<persName ref="#p0284" type="pec">\g<0></persName>', text)
    text = re.sub(p0285, r'<persName ref="#p0285" type="pec">\g<0></persName>', text)
    text = re.sub(p0286, r'<persName ref="#p0286" type="pec">\g<0></persName>', text)
    text = re.sub(p0287, r'<persName ref="#p0287" type="pec">\g<0></persName>', text)
    text = re.sub(p0288, r'<persName ref="#p0288" type="pec">\g<0></persName>', text)
    text = re.sub(p0289, r'<persName ref="#p0289" type="pec">\g<0></persName>', text)
    text = re.sub(p0290, r'<persName ref="#p0290" type="pec">\g<0></persName>', text)
    text = re.sub(p0292, r'<persName ref="#p0292" type="pec">\g<0></persName>', text)
    text = re.sub(p0293, r'<persName ref="#p0293" type="pec">\g<0></persName>', text)
    text = re.sub(p0294, r'<persName ref="#p0294" type="pec">\g<0></persName>', text)
    text = re.sub(p0295, r'<persName ref="#p0295" type="pec">\g<0></persName>', text)
    text = re.sub(p0296, r'<persName ref="#p0296" type="pec">\g<0></persName>', text)
    text = re.sub(p0297, r'<persName ref="#p0297" type="pec">\g<0></persName>', text)
    text = re.sub(p0298, r'<persName ref="#p0298" type="pec">\g<0></persName>', text)
    text = re.sub(p0299, r'<persName ref="#p0299" type="pec">\g<0></persName>', text)
    text = re.sub(p0300, r'<persName ref="#p0300" type="pec">\g<0></persName>', text)
    text = re.sub(p0302, r'<persName ref="#p0302" type="pec">\g<0></persName>', text)
    text = re.sub(p0303, r'<persName ref="#p0303" type="pec">\g<0></persName>', text)
    text = re.sub(p0304, r'<persName ref="#p0304" type="pec">\g<0></persName>', text)
    text = re.sub(p0305, r'<persName ref="#p0305" type="pec">\g<0></persName>', text)
    text = re.sub(p0306, r'<persName ref="#p0306" type="pec">\g<0></persName>', text)
    text = re.sub(p0307, r'<persName ref="#p0307" type="pec">\g<0></persName>', text)
    text = re.sub(p0308, r'<persName ref="#p0308" type="pec">\g<0></persName>', text)
    text = re.sub(p0309, r'<persName ref="#p0309" type="pec">\g<0></persName>', text)
    text = re.sub(p0310, r'<persName ref="#p0310" type="pec">\g<0></persName>', text)
    text = re.sub(p0311, r'<persName ref="#p0311" type="pec">\g<0></persName>', text)
    text = re.sub(p0312, r'<persName ref="#p0312" type="pec">\g<0></persName>', text)
    text = re.sub(p0313, r'<persName ref="#p0313" type="pec">\g<0></persName>', text)
    text = re.sub(p0314, r'<persName ref="#p0314" type="pec">\g<0></persName>', text)
    text = re.sub(p0316, r'<persName ref="#p0316" type="pec">\g<0></persName>', text)
    text = re.sub(p0317, r'<persName ref="#p0317" type="pec">\g<0></persName>', text)
    text = re.sub(p0318, r'<persName ref="" type="pec">\g<0></persName>', text)
    text = re.sub(p0319, r'<persName ref="#p0319" type="pec">\g<0></persName>', text)
    text = re.sub(p0320, r'<persName ref="#p0320" type="pec">\g<0></persName>', text)
    text = re.sub(p0321, r'<persName ref="#p0321" type="pec">\g<0></persName>', text)
    text = re.sub(p0322, r'<persName ref="#p0322" type="pec">\g<0></persName>', text)
    text = re.sub(p0323, r'<persName ref="#p0323" type="pec">\g<0></persName>', text)
    text = re.sub(p0325, r'<persName ref="#p0325" type="pec">\g<0></persName>', text)
    text = re.sub(p0326, r'<persName ref="#p0326" type="pec">\g<0></persName>', text)
    text = re.sub(p0327, r'<persName ref="#p0327" type="pec">\g<0></persName>', text)
    text = re.sub(p0328, r'<persName ref="#p0328" type="pec">\g<0></persName>', text)
    text = re.sub(p0329, r'<persName ref="#p0329" type="pec">\g<0></persName>', text)
    text = re.sub(p0331, r'<persName ref="#p0331" type="pec">\g<0></persName>', text)
    text = re.sub(p0332, r'<persName ref="#p0332" type="pec">\g<0></persName>', text)
    text = re.sub(p0334, r'<persName ref="#p0334" type="pec">\g<0></persName>', text)
    text = re.sub(p0335, r'<persName ref="" type="pec">\g<0></persName>', text)
    text = re.sub(p0338, r'<persName ref="#p0338" type="pec">\g<0></persName>', text)
    text = re.sub(p0339, r'<persName ref="#p0339" type="pec">\g<0></persName>', text)
    text = re.sub(p0340, r'<persName ref="#p0340" type="pec">\g<0></persName>', text)
    text = re.sub(p0342, r'<persName ref="#p0342" type="pec">\g<0></persName>', text)
    text = re.sub(p0343, r'<persName ref="#p0343" type="pec">\g<0></persName>', text)
    text = re.sub(p0344, r'<persName ref="#p0344" type="pec">\g<0></persName>', text)
    text = re.sub(p0345, r'<persName ref="#p0345" type="pec">\g<0></persName>', text)
    text = re.sub(p0346, r'<persName ref="#p0346" type="pec">\g<0></persName>', text)
    text = re.sub(p0348, r'<persName ref="#p0348" type="pec">\g<0></persName>', text)
    text = re.sub(p0349, r'<persName ref="#p0349" type="pec">\g<0></persName>', text)
    text = re.sub(p0350, r'<persName ref="#p0350" type="pec">\g<0></persName>', text)
    text = re.sub(p0351, r'<persName ref="#p0351" type="pec">\g<0></persName>', text)
    text = re.sub(p0352, r'<persName ref="#p0352" type="pec">\g<0></persName>', text)
    text = re.sub(p0353, r'<persName ref="#p0353" type="pec">\g<0></persName>', text)
    text = re.sub(p0354, r'<persName ref="#p0354" type="pec">\g<0></persName>', text)
    text = re.sub(p0355, r'<persName ref="#p0355" type="pec">\g<0></persName>', text)
    text = re.sub(p0356, r'<persName ref="#p0356" type="pec">\g<0></persName>', text)
    text = re.sub(p0357, r'<persName ref="#p0357" type="pec">\g<0></persName>', text)
    text = re.sub(p0358, r'<persName ref="#p0358" type="pec">\g<0></persName>', text)
    text = re.sub(p0359, r'<persName ref="#p0359" type="pec">\g<0></persName>', text)
    text = re.sub(p0360, r'<persName ref="#p0360" type="pec">\g<0></persName>', text)
    text = re.sub(p0361, r'<persName ref="#p0361" type="pec">\g<0></persName>', text)
    text = re.sub(p0362, r'<persName ref="#p0362" type="pec">\g<0></persName>', text)
    text = re.sub(p0363, r'<persName ref="#p0363" type="pec">\g<0></persName>', text)
    text = re.sub(p0364, r'<persName ref="#p0364" type="pec">\g<0></persName>', text)
    text = re.sub(p0365, r'<persName ref="#p0365" type="pec">\g<0></persName>', text)
    text = re.sub(p0366, r'<persName ref="#p0366" type="pec">\g<0></persName>', text)
    text = re.sub(p0367, r'<persName ref="#p0367" type="pec">\g<0></persName>', text)
    text = re.sub(p0368, r'<persName ref="#p0368" type="pec">\g<0></persName>', text)
    text = re.sub(p0369, r'<persName ref="#p0369" type="pec">\g<0></persName>', text)
    text = re.sub(p0370, r'<persName ref="#p0370" type="pec">\g<0></persName>', text)
    text = re.sub(p0371, r'<persName ref="#p0371" type="pec">\g<0></persName>', text)
    text = re.sub(p0372, r'<persName ref="#p0372" type="pec">\g<0></persName>', text)
    text = re.sub(p0373, r'<persName ref="#p0373" type="pec">\g<0></persName>', text)
    text = re.sub(p0374, r'<persName ref="#p0374" type="pec">\g<0></persName>', text)
    text = re.sub(p0376, r'<persName ref="#p0376" type="pec">\g<0></persName>', text)
    text = re.sub(p0377, r'<persName ref="#p0377" type="pec">\g<0></persName>', text)
    text = re.sub(p0378, r'<persName ref="#p0378" type="pec">\g<0></persName>', text)
    text = re.sub(p0379, r'<persName ref="#p0379" type="pec">\g<0></persName>', text)
    text = re.sub(p0380, r'<persName ref="#p0380" type="pec">\g<0></persName>', text)
    text = re.sub(p0381, r'<persName ref="#p0381" type="pec">\g<0></persName>', text)
    text = re.sub(p0382, r'<persName ref="" type="pec">\g<0></persName>', text)
    text = re.sub(p0384, r'<persName ref="#p0384" type="pec">\g<0></persName>', text)
    text = re.sub(p0385, r'<persName ref="#p0385" type="pec">\g<0></persName>', text)
    text = re.sub(p0386, r'<persName ref="#p0386" type="pec">\g<0></persName>', text)
    text = re.sub(p0387, r'<persName ref="#p0387" type="pec">\g<0></persName>', text)
    text = re.sub(p0388, r'<persName ref="#p0388" type="pec">\g<0></persName>', text)
    text = re.sub(p0389, r'<persName ref="#p0389" type="pec">\g<0></persName>', text)
    text = re.sub(p0390, r'<persName ref="#p0390" type="pec">\g<0></persName>', text)
    text = re.sub(p0393, r'<persName ref="#p0393" type="pec">\g<0></persName>', text)
    text = re.sub(p0394, r'<persName ref="#p0394" type="pec">\g<0></persName>', text)
    text = re.sub(p0395, r'<persName ref="#p0395" type="pec">\g<0></persName>', text)
    text = re.sub(p0396, r'<persName ref="#p0396" type="pec">\g<0></persName>', text)
    text = re.sub(p0397, r'<persName ref="#p0397" type="pec">\g<0></persName>', text)
    text = re.sub(p0398, r'<persName ref="#p0398" type="pec">\g<0></persName>', text)
    text = re.sub(p0399, r'<persName ref="#p0399" type="pec">\g<0></persName>', text)
    text = re.sub(p0400, r'<persName ref="#p0400" type="pec">\g<0></persName>', text)
    text = re.sub(p0401, r'<persName ref="#p0401" type="pec">\g<0></persName>', text)
    text = re.sub(p0402, r'<persName ref="#p0402" type="pec">\g<0></persName>', text)
    text = re.sub(p0403, r'<persName ref="#p0403" type="pec">\g<0></persName>', text)
    text = re.sub(p0404, r'<persName ref="#p0404" type="pec">\g<0></persName>', text)
    text = re.sub(p0405, r'<persName ref="#p0405" type="pec">\g<0></persName>', text)
    text = re.sub(p0406, r'<persName ref="#p0406" type="pec">\g<0></persName>', text)
    text = re.sub(p0407, r'<persName ref="#p0407" type="pec">\g<0></persName>', text)
    text = re.sub(p0408, r'<persName ref="#p0408" type="pec">\g<0></persName>', text)
    text = re.sub(p0409, r'<persName ref="#p0409" type="pec">\g<0></persName>', text)
    text = re.sub(p0410, r'<persName ref="#p0410" type="pec">\g<0></persName>', text)
    text = re.sub(p0411, r'<persName ref="#p0411" type="pec">\g<0></persName>', text)
    text = re.sub(p0412, r'<persName ref="#p0412" type="pec">\g<0></persName>', text)
    text = re.sub(p0413, r'<persName ref="#p0413" type="pec">\g<0></persName>', text)
    text = re.sub(p0414, r'<persName ref="#p0414" type="pec">\g<0></persName>', text)
    text = re.sub(p0415, r'<persName ref="#p0415" type="pec">\g<0></persName>', text)
    text = re.sub(p0416, r'<persName ref="#p0416" type="pec">\g<0></persName>', text)
    text = re.sub(p0417, r'<persName ref="#p0417" type="pec">\g<0></persName>', text)
    text = re.sub(p0418, r'<persName ref="#p0418" type="pec">\g<0></persName>', text)
    text = re.sub(p0419, r'<persName ref="#p0419" type="pec">\g<0></persName>', text)
    text = re.sub(p0420, r'<persName ref="#p0420" type="pec">\g<0></persName>', text)
    text = re.sub(p0421, r'<persName ref="#p0421" type="pec">\g<0></persName>', text)
    text = re.sub(p0422, r'<persName ref="#p0422" type="pec">\g<0></persName>', text)
    text = re.sub(p0423, r'<persName ref="#p0423" type="pec">\g<0></persName>', text)
    text = re.sub(p0424, r'<persName ref="#p0424" type="pec">\g<0></persName>', text)
    text = re.sub(p0425, r'<persName ref="#p0425" type="pec">\g<0></persName>', text)
    text = re.sub(p0426, r'<persName ref="#p0426" type="pec">\g<0></persName>', text)
    text = re.sub(p0427, r'<persName ref="#p0427" type="pec">\g<0></persName>', text)
    text = re.sub(p0428, r'<persName ref="#p0428" type="pec">\g<0></persName>', text)
    text = re.sub(p0429, r'<persName ref="#p0429" type="pec">\g<0></persName>', text)
    text = re.sub(p0430, r'<persName ref="#p0430" type="pec">\g<0></persName>', text)
    text = re.sub(p0431, r'<persName ref="#p0431" type="pec">\g<0></persName>', text)
    text = re.sub(p0432, r'<persName ref="#p0432" type="pec">\g<0></persName>', text)
    text = re.sub(p0433, r'<persName ref="#p0433" type="pec">\g<0></persName>', text)
    text = re.sub(p0434, r'<persName ref="#p0434" type="pec">\g<0></persName>', text)
    text = re.sub(p0435, r'<persName ref="#p0435" type="pec">\g<0></persName>', text)
    text = re.sub(p0436, r'<persName ref="#p0436" type="pec">\g<0></persName>', text)
    text = re.sub(p0437, r'<persName ref="#p0437" type="pec">\g<0></persName>', text)
    text = re.sub(p0438, r'<persName ref="#p0438" type="pec">\g<0></persName>', text)
    text = re.sub(p0439, r'<persName ref="#p0439" type="pec">\g<0></persName>', text)
    text = re.sub(p0440, r'<persName ref="#p0440" type="pec">\g<0></persName>', text)
    text = re.sub(p0441, r'<persName ref="#p0441" type="pec">\g<0></persName>', text)
    text = re.sub(p0442, r'<persName ref="#p0442" type="pec">\g<0></persName>', text)
    text = re.sub(p0443, r'<persName ref="#p0443" type="pec">\g<0></persName>', text)
    text = re.sub(p0444, r'<persName ref="#p0444" type="pec">\g<0></persName>', text)
    text = re.sub(p0445, r'<persName ref="#p0445" type="pec">\g<0></persName>', text)
    text = re.sub(p0446, r'<persName ref="#p0446" type="pec">\g<0></persName>', text)
    text = re.sub(p0447, r'<persName ref="#p0447" type="pec">\g<0></persName>', text)
    text = re.sub(p0448, r'<persName ref="#p0448" type="pec">\g<0></persName>', text)
    text = re.sub(p0449, r'<persName ref="#p0449" type="pec">\g<0></persName>', text)
    text = re.sub(p0450, r'<persName ref="#p0450" type="pec">\g<0></persName>', text)
    text = re.sub(p0451, r'<persName ref="#p0451" type="pec">\g<0></persName>', text)
    text = re.sub(p0452, r'<persName ref="#p0452" type="pec">\g<0></persName>', text)
    text = re.sub(p0453, r'<persName ref="#p0453" type="pec">\g<0></persName>', text)
    text = re.sub(p0454, r'<persName ref="#p0454" type="pec">\g<0></persName>', text)
    text = re.sub(p0455, r'<persName ref="#p0455" type="pec">\g<0></persName>', text)
    text = re.sub(p0456, r'<persName ref="#p0456" type="pec">\g<0></persName>', text)
    text = re.sub(p0457, r'<persName ref="#p0457" type="pec">\g<0></persName>', text)
    text = re.sub(p0458, r'<persName ref="#p0458" type="pec">\g<0></persName>', text)
    text = re.sub(p0459, r'<persName ref="#p0459" type="pec">\g<0></persName>', text)
    text = re.sub(p0460, r'<persName ref="#p0460" type="pec">\g<0></persName>', text)
    text = re.sub(p0461, r'<persName ref="#p0461" type="pec">\g<0></persName>', text)
    text = re.sub(p0462, r'<persName ref="#p0462" type="pec">\g<0></persName>', text)
    text = re.sub(p0463, r'<persName ref="#p0463" type="pec">\g<0></persName>', text)
    text = re.sub(p0464, r'<persName ref="#p0464" type="pec">\g<0></persName>', text)
    text = re.sub(p0465, r'<persName ref="#p0465" type="pec">\g<0></persName>', text)
    text = re.sub(p0466, r'<persName ref="#p0466" type="pec">\g<0></persName>', text)
    text = re.sub(p0467, r'<persName ref="#p0467" type="pec">\g<0></persName>', text)
    text = re.sub(p0468, r'<persName ref="#p0468" type="pec">\g<0></persName>', text)
    text = re.sub(p0469, r'<persName ref="#p0469" type="pec">\g<0></persName>', text)
    text = re.sub(p0470, r'<persName ref="#p0470" type="pec">\g<0></persName>', text)
    text = re.sub(p0471, r'<persName ref="#p0471" type="pec">\g<0></persName>', text)
    text = re.sub(p0472, r'<persName ref="#p0472" type="pec">\g<0></persName>', text)
    text = re.sub(p0473, r'<persName ref="#p0473" type="pec">\g<0></persName>', text)
    text = re.sub(p0474, r'<persName ref="#p0474" type="pec">\g<0></persName>', text)
    text = re.sub(p0475, r'<persName ref="#p0475" type="pec">\g<0></persName>', text)
    text = re.sub(p0476, r'<persName ref="#p0476" type="pec">\g<0></persName>', text)
    text = re.sub(p0477, r'<persName ref="#p0477" type="pec">\g<0></persName>', text)
    text = re.sub(p0478, r'<persName ref="#p0478" type="pec">\g<0></persName>', text)
    text = re.sub(p0479, r'<persName ref="#p0479" type="pec">\g<0></persName>', text)
    text = re.sub(p0481, r'<persName ref="#p0481" type="pec">\g<0></persName>', text)
    text = re.sub(p0483, r'<persName ref="#p0483" type="pec">\g<0></persName>', text)
    text = re.sub(p0484, r'<persName ref="#p0484" type="pec">\g<0></persName>', text)
    text = re.sub(p0485, r'<persName ref="#p0485" type="pec">\g<0></persName>', text)
    text = re.sub(p0486, r'<persName ref="#p0486" type="pec">\g<0></persName>', text)
    text = re.sub(p0487, r'<persName ref="#p0487" type="pec">\g<0></persName>', text)
    text = re.sub(p0488, r'<persName ref="#p0488" type="pec">\g<0></persName>', text)
    text = re.sub(p0489, r'<persName ref="#p0489" type="pec">\g<0></persName>', text)
    text = re.sub(p0490, r'<persName ref="#p0490" type="pec">\g<0></persName>', text)
    text = re.sub(p0491, r'<persName ref="#p0491" type="pec">\g<0></persName>', text)
    text = re.sub(p0492, r'<persName ref="#p0492" type="pec">\g<0></persName>', text)
    text = re.sub(p0493, r'<persName ref="#p0493" type="pec">\g<0></persName>', text)
    text = re.sub(p0494, r'<persName ref="#p0494" type="pec">\g<0></persName>', text)
    text = re.sub(p0495, r'<persName ref="#p0495" type="pec">\g<0></persName>', text)
    text = re.sub(p0496, r'<persName ref="#p0496" type="pec">\g<0></persName>', text)
    text = re.sub(p0497, r'<persName ref="#p0497" type="pec">\g<0></persName>', text)
    text = re.sub(p0498, r'<persName ref="#p0498" type="pec">\g<0></persName>', text)
    text = re.sub(p0499, r'<persName ref="#p0499" type="pec">\g<0></persName>', text)
    text = re.sub(p0500, r'<persName ref="#p0500" type="pec">\g<0></persName>', text)
    text = re.sub(p0501, r'<persName ref="#p0501" type="pec">\g<0></persName>', text)
    text = re.sub(p0503, r'<persName ref="#p0503" type="pec">\g<0></persName>', text)
    text = re.sub(p0504, r'<persName ref="#p0504" type="pec">\g<0></persName>', text)
    text = re.sub(p0505, r'<persName ref="#p0505" type="pec">\g<0></persName>', text)
    text = re.sub(p0506, r'<persName ref="#p0506" type="pec">\g<0></persName>', text)
    text = re.sub(p0508, r'<persName ref="#p0508" type="pec">\g<0></persName>', text)
    text = re.sub(p0509, r'<persName ref="#p0509" type="pec">\g<0></persName>', text)
    text = re.sub(p0510, r'<persName ref="#p0510" type="pec">\g<0></persName>', text)
    text = re.sub(p0511, r'<persName ref="#p0511" type="pec">\g<0></persName>', text)
    text = re.sub(p0512, r'<persName ref="#p0512" type="pec">\g<0></persName>', text)
    text = re.sub(p0513, r'<persName ref="#p0513" type="pec">\g<0></persName>', text)
    text = re.sub(p0515, r'<persName ref="#p0515" type="pec">\g<0></persName>', text)
    text = re.sub(p0516, r'<persName ref="#p0516" type="pec">\g<0></persName>', text)
    text = re.sub(p0517, r'<persName ref="#p0517" type="pec">\g<0></persName>', text)
    text = re.sub(p0518, r'<persName ref="#p0518" type="pec">\g<0></persName>', text)
    text = re.sub(p0519, r'<persName ref="#p0519" type="pec">\g<0></persName>', text)
    text = re.sub(p0520, r'<persName ref="#p0520" type="pec">\g<0></persName>', text)
    text = re.sub(p0521, r'<persName ref="#p0521" type="pec">\g<0></persName>', text)
    text = re.sub(p0522, r'<persName ref="#p0522" type="pec">\g<0></persName>', text)
    text = re.sub(p0523, r'<persName ref="#p0523" type="pec">\g<0></persName>', text)
    text = re.sub(p0524, r'<persName ref="#p0524" type="pec">\g<0></persName>', text)
    text = re.sub(p0525, r'<persName ref="#p0525" type="pec">\g<0></persName>', text)
    text = re.sub(p0526, r'<persName ref="#p0526" type="pec">\g<0></persName>', text)
    text = re.sub(p0527, r'<persName ref="#p0527" type="pec">\g<0></persName>', text)
    text = re.sub(p0528, r'<persName ref="#p0528" type="pec">\g<0></persName>', text)
    text = re.sub(p0529, r'<persName ref="#p0529" type="pec">\g<0></persName>', text)
    text = re.sub(p0530, r'<persName ref="#p0530" type="pec">\g<0></persName>', text)
    text = re.sub(p0531, r'<persName ref="#p0531" type="pec">\g<0></persName>', text)
    text = re.sub(p0532, r'<persName ref="#p0532" type="pec">\g<0></persName>', text)
    text = re.sub(p0533, r'<persName ref="#p0533" type="pec">\g<0></persName>', text)
    text = re.sub(p0534, r'<persName ref="#p0534" type="pec">\g<0></persName>', text)
    text = re.sub(p0535, r'<persName ref="#p0535" type="pec">\g<0></persName>', text)
    text = re.sub(p0536, r'<persName ref="" type="pec">\g<0></persName>', text)
    text = re.sub(p0538, r'<persName ref="#p0538" type="pec">\g<0></persName>', text)
    text = re.sub(p0539, r'<persName ref="#p0539" type="pec">\g<0></persName>', text)
    text = re.sub(p0540, r'<persName ref="#p0540" type="pec">\g<0></persName>', text)
    text = re.sub(p0541, r'<persName ref="#p0541" type="pec">\g<0></persName>', text)
    text = re.sub(p0542, r'<persName ref="#p0542" type="pec">\g<0></persName>', text)
    text = re.sub(p0543, r'<persName ref="#p0543" type="pec">\g<0></persName>', text)
    text = re.sub(p0544, r'<persName ref="#p0544" type="pec">\g<0></persName>', text)
    text = re.sub(p0545, r'<persName ref="#p0545" type="pec">\g<0></persName>', text)
    text = re.sub(p0546, r'<persName ref="#p0546" type="pec">\g<0></persName>', text)
    text = re.sub(p0547, r'<persName ref="#p0547" type="pec">\g<0></persName>', text)
    text = re.sub(p0548, r'<persName ref="#p0548" type="pec">\g<0></persName>', text)
    text = re.sub(p0549, r'<persName ref="#p0549" type="pec">\g<0></persName>', text)
    text = re.sub(p0550, r'<persName ref="#p0550" type="pec">\g<0></persName>', text)
    text = re.sub(p0551, r'<persName ref="#p0551" type="pec">\g<0></persName>', text)
    text = re.sub(p0552, r'<persName ref="#p0552" type="pec">\g<0></persName>', text)
    text = re.sub(p0553, r'<persName ref="#p0553" type="pec">\g<0></persName>', text)
    text = re.sub(p0554, r'<persName ref="#p0554" type="pec">\g<0></persName>', text)
    text = re.sub(p0555, r'<persName ref="#p0555" type="pec">\g<0></persName>', text)
    text = re.sub(p0556, r'<persName ref="#p0556" type="pec">\g<0></persName>', text)
    text = re.sub(p0557, r'<persName ref="#p0557" type="pec">\g<0></persName>', text)
    text = re.sub(p0558, r'<persName ref="#p0558" type="pec">\g<0></persName>', text)
    text = re.sub(p0559, r'<persName ref="#p0559" type="pec">\g<0></persName>', text)
    text = re.sub(p0560, r'<persName ref="#p0560" type="pec">\g<0></persName>', text)
    text = re.sub(p0561, r'<persName ref="#p0561" type="pec">\g<0></persName>', text)
    text = re.sub(p0563, r'<persName ref="#p0563" type="pec">\g<0></persName>', text)
    text = re.sub(p0564, r'<persName ref="#p0564" type="pec">\g<0></persName>', text)
    text = re.sub(p0565, r'<persName ref="#p0565" type="pec">\g<0></persName>', text)
    text = re.sub(p0566, r'<persName ref="#p0566" type="pec">\g<0></persName>', text)
    text = re.sub(p0567, r'<persName ref="#p0567" type="pec">\g<0></persName>', text)
    text = re.sub(p0568, r'<persName ref="#p0568" type="pec">\g<0></persName>', text)
    text = re.sub(p0569, r'<persName ref="#p0569" type="pec">\g<0></persName>', text)
    text = re.sub(p0570, r'<persName ref="#p0570" type="pec">\g<0></persName>', text)
    text = re.sub(p0571, r'<persName ref="#p0571" type="pec">\g<0></persName>', text)
    text = re.sub(p0572, r'<persName ref="#p0572" type="pec">\g<0></persName>', text)
    text = re.sub(p0573, r'<persName ref="#p0573" type="pec">\g<0></persName>', text)
    text = re.sub(p0574, r'<persName ref="#p0574" type="pec">\g<0></persName>', text)
    text = re.sub(p0575, r'<persName ref="#p0575" type="pec">\g<0></persName>', text)
    text = re.sub(p0576, r'<persName ref="#p0576" type="pec">\g<0></persName>', text)
    text = re.sub(p0577, r'<persName ref="#p0577" type="pec">\g<0></persName>', text)
    text = re.sub(p0578, r'<persName ref="#p0578" type="pec">\g<0></persName>', text)
    text = re.sub(p0579, r'<persName ref="#p0579" type="pec">\g<0></persName>', text)
    text = re.sub(p0580, r'<persName ref="#p0580" type="pec">\g<0></persName>', text)
    text = re.sub(p0581, r'<persName ref="#p0581" type="pec">\g<0></persName>', text)
    text = re.sub(p0582, r'<persName ref="#p0582" type="pec">\g<0></persName>', text)
    text = re.sub(p0583, r'<persName ref="#p0583" type="pec">\g<0></persName>', text)
    text = re.sub(p0584, r'<persName ref="#p0584" type="pec">\g<0></persName>', text)
    text = re.sub(p0585, r'<persName ref="#p0585" type="pec">\g<0></persName>', text)
    text = re.sub(p0586, r'<persName ref="#p0586" type="pec">\g<0></persName>', text)
    text = re.sub(p0587, r'<persName ref="#p0587" type="pec">\g<0></persName>', text)
    text = re.sub(p0588, r'<persName ref="#p0588" type="pec">\g<0></persName>', text)
    text = re.sub(p0589, r'<persName ref="#p0589" type="pec">\g<0></persName>', text)
    text = re.sub(p0590, r'<persName ref="" type="pec">\g<0></persName>', text)
    text = re.sub(p0592, r'<persName ref="#p0592" type="pec">\g<0></persName>', text)
    text = re.sub(p0593, r'<persName ref="#p0593" type="pec">\g<0></persName>', text)
    text = re.sub(p0594, r'<persName ref="#p0594" type="pec">\g<0></persName>', text)
    text = re.sub(p0595, r'<persName ref="#p0595" type="pec">\g<0></persName>', text)
    text = re.sub(p0596, r'<persName ref="#p0596" type="pec">\g<0></persName>', text)
    text = re.sub(p0597, r'<persName ref="#p0597" type="pec">\g<0></persName>', text)
    text = re.sub(p0598, r'<persName ref="#p0598" type="pec">\g<0></persName>', text)
    text = re.sub(p0599, r'<persName ref="#p0599" type="pec">\g<0></persName>', text)
    text = re.sub(p0600, r'<persName ref="#p0600" type="pec">\g<0></persName>', text)
    text = re.sub(p0601, r'<persName ref="#p0601" type="pec">\g<0></persName>', text)
    text = re.sub(p0602, r'<persName ref="#p0602" type="pec">\g<0></persName>', text)
    text = re.sub(p0603, r'<persName ref="#p0603" type="pec">\g<0></persName>', text)
    text = re.sub(p0604, r'<persName ref="#p0604" type="pec">\g<0></persName>', text)
    text = re.sub(p0605, r'<persName ref="#p0605" type="pec">\g<0></persName>', text)
    text = re.sub(p0606, r'<persName ref="#p0606" type="pec">\g<0></persName>', text)
    text = re.sub(p0607, r'<persName ref="#p0607" type="pec">\g<0></persName>', text)
    text = re.sub(p0608, r'<persName ref="#p0608" type="pec">\g<0></persName>', text)
    text = re.sub(p0609, r'<persName ref="#p0609" type="pec">\g<0></persName>', text)
    text = re.sub(p0610, r'<persName ref="#p0610" type="pec">\g<0></persName>', text)
    text = re.sub(p0611, r'<persName ref="#p0611" type="pec">\g<0></persName>', text)
    text = re.sub(p0612, r'<persName ref="#p0612" type="pec">\g<0></persName>', text)
    text = re.sub(p0613, r'<persName ref="#p0613" type="pec">\g<0></persName>', text)
    text = re.sub(p0614, r'<persName ref="#p0614" type="pec">\g<0></persName>', text)
    text = re.sub(p0615, r'<persName ref="#p0615" type="pec">\g<0></persName>', text)
    text = re.sub(p0616, r'<persName ref="#p0616" type="pec">\g<0></persName>', text)
    text = re.sub(p0617, r'<persName ref="#p0617" type="pec">\g<0></persName>', text)
    text = re.sub(p0618, r'<persName ref="#p0618" type="pec">\g<0></persName>', text)
    text = re.sub(p0619, r'<persName ref="#p0619" type="pec">\g<0></persName>', text)
    text = re.sub(p0620, r'<persName ref="#p0620" type="pec">\g<0></persName>', text)
    text = re.sub(p0621, r'<persName ref="#p0621" type="pec">\g<0></persName>', text)
    text = re.sub(p0623, r'<persName ref="#p0623" type="pec">\g<0></persName>', text)
    text = re.sub(p0624, r'<persName ref="#p0624" type="pec">\g<0></persName>', text)
    text = re.sub(p0625, r'<persName ref="#p0625" type="pec">\g<0></persName>', text)
    text = re.sub(p0626, r'<persName ref="#p0626" type="pec">\g<0></persName>', text)
    text = re.sub(p0627, r'<persName ref="#p0627" type="pec">\g<0></persName>', text)
    text = re.sub(p0628, r'<persName ref="#p0628" type="pec">\g<0></persName>', text)
    text = re.sub(p0630, r'<persName ref="#p0630" type="pec">\g<0></persName>', text)
    text = re.sub(p0631, r'<persName ref="#p0631" type="pec">\g<0></persName>', text)
    text = re.sub(p0632, r'<persName ref="#p0632" type="pec">\g<0></persName>', text)
    text = re.sub(p0633, r'<persName ref="#p0633" type="pec">\g<0></persName>', text)
    text = re.sub(p0634, r'<persName ref="#p0634" type="pec">\g<0></persName>', text)
    text = re.sub(p0635, r'<persName ref="#p0635" type="pec">\g<0></persName>', text)
    text = re.sub(p0636, r'<persName ref="#p0636" type="pec">\g<0></persName>', text)
    text = re.sub(p0637, r'<persName ref="#p0637" type="pec">\g<0></persName>', text)
    text = re.sub(p0639, r'<persName ref="#p0639" type="pec">\g<0></persName>', text)
    text = re.sub(p0640, r'<persName ref="#p0640" type="pec">\g<0></persName>', text)
    text = re.sub(p0641, r'<persName ref="#p0641" type="pec">\g<0></persName>', text)
    text = re.sub(p0642, r'<persName ref="#p0642" type="pec">\g<0></persName>', text)
    text = re.sub(p0643, r'<persName ref="#p0643" type="pec">\g<0></persName>', text)
    text = re.sub(p0644, r'<persName ref="#p0644" type="pec">\g<0></persName>', text)
    text = re.sub(p0645, r'<persName ref="#p0645" type="pec">\g<0></persName>', text)
    text = re.sub(p0646, r'<persName ref="#p0646" type="pec">\g<0></persName>', text)
    text = re.sub(p0647, r'<persName ref="" type="pec">\g<0></persName>', text)
    text = re.sub(p0648, r'<persName ref="#p0648" type="pec">\g<0></persName>', text)
    text = re.sub(p0649, r'<persName ref="#p0649" type="pec">\g<0></persName>', text)
    text = re.sub(p0650, r'<persName ref="#p0650" type="pec">\g<0></persName>', text)
    text = re.sub(p0651, r'<persName ref="#p0651" type="pec">\g<0></persName>', text)
    text = re.sub(p0652, r'<persName ref="#p0652" type="pec">\g<0></persName>', text)
    text = re.sub(p0653, r'<persName ref="#p0653" type="pec">\g<0></persName>', text)
    text = re.sub(p0654, r'<persName ref="#p0654" type="pec">\g<0></persName>', text)
    text = re.sub(p0655, r'<persName ref="#p0655" type="pec">\g<0></persName>', text)
    text = re.sub(p0656, r'<persName ref="#p0656" type="pec">\g<0></persName>', text)
    text = re.sub(p0657, r'<persName ref="#p0657" type="pec">\g<0></persName>', text)
    text = re.sub(p0658, r'<persName ref="#p0658" type="pec">\g<0></persName>', text)
    text = re.sub(p0660, r'<persName ref="#p0660" type="pec">\g<0></persName>', text)
    text = re.sub(p0661, r'<persName ref="#p0661" type="pec">\g<0></persName>', text)
    text = re.sub(p0662, r'<persName ref="#p0662" type="pec">\g<0></persName>', text)
    text = re.sub(p0663, r'<persName ref="#p0663" type="pec">\g<0></persName>', text)
    text = re.sub(p0664, r'<persName ref="#p0664" type="pec">\g<0></persName>', text)
    return text